import A4.DirectMomentsAudit
import A4.DirectMomentsGaussianGram
import A4.DirectMomentsEntryPolynomial

#print axioms MatsumotoPaper.natDegree_directionalMomentPolynomial_le
#print axioms MatsumotoPaper.directionalMomentPolynomial_eq_of_samples
#print axioms MatsumotoPaper.W_d.integral_traceObservable_pow_eq_eval_momentPolynomial
#print axioms MatsumotoPaper.integral_gaussian_linear_product_eq_canonicalMatchings
#print axioms MatsumotoPaper.integrable_complexAuxiliaryFieldProduct_standardGaussian
#print axioms MatsumotoPaper.integral_gaussian_linear_product_eq_pairPartitions
#print axioms MatsumotoPaper.sum_maskedGaussianCoefficients_mul
#print axioms MatsumotoPaper.complexAuxiliaryFieldProduct_masked
#print axioms MatsumotoPaper.product_gaussianGramSlot_eq_pairColoringSum
#print axioms MatsumotoPaper.integrable_product_gaussianGramSlot
#print axioms MatsumotoPaper.integral_product_gaussianGramSlot_eq_coloredPairPartitions
#print axioms MatsumotoPaper.integral_product_gaussianGramSlot_eq_loop_moments
#print axioms MatsumotoPaper.eval_observableMomentPolynomial
#print axioms MatsumotoPaper.coeff_observableMomentPolynomial
#print axioms MatsumotoPaper.allOnesExponent_apply
#print axioms MatsumotoPaper.allOnesExponent_sum
#print axioms MatsumotoPaper.allOnesExponent_multinomial
#print axioms MatsumotoPaper.coeff_allOnes_observableMomentPolynomial
#print axioms MatsumotoPaper.mixed_moment_eq_of_linear_combination_moments
#print axioms MatsumotoPaper.natDegree_momentPolynomialOver_le
#print axioms MatsumotoPaper.map_momentPolynomialOver
#print axioms MatsumotoPaper.iteratedDeriv_polynomial_eval
#print axioms MatsumotoPaper.iteratedDeriv_polynomial_eval_zero
#print axioms MatsumotoPaper.momentPolynomialOver_directionDetPolynomial
#print axioms MatsumotoPaper.traceObservable_traceDirectionCombination
#print axioms MatsumotoPaper.map_mixedDirectionDetPolynomial
#print axioms MatsumotoPaper.eval_eval_mixedDirectionMomentPolynomial
#print axioms MatsumotoPaper.W_d.eval_mixedDirectionMomentPolynomial
#print axioms MatsumotoPaper.polynomialDirectionCoefficient_monomial
#print axioms MatsumotoPaper.coeff_polynomialDirectionCoefficient
#print axioms MatsumotoPaper.natDegree_polynomialDirectionCoefficient_le
#print axioms MatsumotoPaper.eval_polynomialDirectionCoefficient
#print axioms MatsumotoPaper.natDegree_mixedShapeMomentPolynomial_le
#print axioms MatsumotoPaper.W_d.integral_prod_traceObservable_eq_eval_mixedShapeMomentPolynomial
#print axioms MatsumotoPaper.natDegree_entryProductShapePolynomial_le
#print axioms MatsumotoPaper.W_d.integral_prod_entries_eq_eval_entryProductShapePolynomial
#print axioms MatsumotoPaper.natDegree_pairPartitionEntryShapePolynomial_le
#print axioms MatsumotoPaper.W_d.integral_pairPartition_entries_eq_eval_shapePolynomial
#print axioms MatsumotoPaper.natDegree_matchingEntryMomentPolynomial_le
#print axioms MatsumotoPaper.eval_matchingEntryMomentPolynomial
#print axioms MatsumotoPaper.pairPartitionEntryShapePolynomial_eq_matching_of_samples
