import LogdetLean.Coherence.PairBeta
import LogdetLean.GammaMellin
import Mathlib.Tactic

/-!
# Exact random-axis Gaussian coordinates for Pearson correlation

This file formalizes the finite-dimensional Gaussian decomposition underlying
Ruben's representation of the non-null Pearson correlation.  If `u` is a
nonzero vector and `v` is standard Gaussian, the signed coordinate of `v`
along `u` is standard normal and is independent of the squared energy
orthogonal to `u`.  The statement is then upgraded from a fixed axis to an
independent random standard-Gaussian axis by a skew-product argument.

No asymptotic or concentration statement is used here.
-/

namespace LogdetLean.Coherence

noncomputable section

open MeasureTheory ProbabilityTheory Module Set
open scoped RealInnerProductSpace

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [FiniteDimensional ℝ E] [MeasurableSpace E] [BorelSpace E]

/-- Signed coordinate of `v` along the (possibly totalized) axis `u`. -/
def gaussianAxisCoordinate (u v : E) : ℝ :=
  inner ℝ u v / ‖u‖

/-- Squared Gaussian energy orthogonal to the line generated by `u`. -/
def gaussianAxisResidualEnergy (u v : E) : ℝ :=
  ‖v‖ ^ 2 - gaussianAxisCoordinate u v ^ 2

/-- The signed coordinate and orthogonal residual energy. -/
def gaussianAxisCoordinates (u v : E) : ℝ × ℝ :=
  (gaussianAxisCoordinate u v, gaussianAxisResidualEnergy u v)

/-- The chi law is represented canonically as the square-root image of the
corresponding chi-square/Gamma law. -/
def chiMeasure (m : ℕ) : Measure ℝ :=
  Measure.map Real.sqrt (gammaMeasure ((m : ℝ) / 2) (1 / 2))

omit [FiniteDimensional ℝ E] in
theorem measurable_gaussianAxisCoordinate (u : E) :
    Measurable (gaussianAxisCoordinate u) := by
  unfold gaussianAxisCoordinate
  fun_prop

theorem measurable_gaussianAxisResidualEnergy (u : E) :
    Measurable (gaussianAxisResidualEnergy u) := by
  unfold gaussianAxisResidualEnergy
  exact measurable_id.norm.pow_const 2 |>.sub
    ((measurable_gaussianAxisCoordinate u).pow_const 2)

theorem measurable_uncurry_gaussianAxisCoordinates :
    Measurable (Function.uncurry (gaussianAxisCoordinates (E := E))) := by
  have hinner : Measurable (fun z : E × E ↦ inner ℝ z.1 z.2) :=
    continuous_inner.measurable
  have hcoordinate : Measurable
      (fun z : E × E ↦ gaussianAxisCoordinate z.1 z.2) := by
    exact hinner.div measurable_fst.norm
  unfold Function.uncurry gaussianAxisCoordinates gaussianAxisResidualEnergy
  exact hcoordinate.prodMk
    (measurable_snd.norm.pow_const 2 |>.sub (hcoordinate.pow_const 2))

/-- The squared norm of the projection onto `span u` is the square of the
signed coordinate along `u`. -/
theorem normSq_spanProjection_eq_axisCoordinate_sq
    (u v : E) (hu : u ≠ 0) :
    ‖(ℝ ∙ u).orthogonalProjectionOnto v‖ ^ 2 =
      gaussianAxisCoordinate u v ^ 2 := by
  change ‖(ℝ ∙ u).starProjection v‖ ^ 2 = _
  rw [Submodule.starProjection_singleton]
  unfold gaussianAxisCoordinate
  rw [norm_smul]
  simp only [RCLike.ofReal_real_eq_id, id_eq]
  have hnorm : ‖u‖ ≠ 0 := norm_ne_zero_iff.mpr hu
  rw [Real.norm_eq_abs, abs_div,
    abs_of_nonneg (sq_nonneg ‖u‖)]
  field_simp [hnorm]
  rw [sq_abs]

/-- The algebraic residual energy is exactly the squared norm of the
orthogonal-complement projection. -/
theorem gaussianAxisResidualEnergy_eq_orthogonalProjection
    (u v : E) (hu : u ≠ 0) :
    gaussianAxisResidualEnergy u v =
      ‖((ℝ ∙ u).orthogonal).orthogonalProjectionOnto v‖ ^ 2 := by
  have hline := normSq_spanProjection_eq_axisCoordinate_sq u v hu
  unfold gaussianAxisResidualEnergy
  rw [← hline]
  apply sub_eq_iff_eq_add.mpr
  simpa [add_comm] using
    (normSq_eq_projection_add_orthogonalComplement (ℝ ∙ u) v)

/-- A unit linear functional of a standard Gaussian has standard normal law. -/
theorem map_gaussianAxisCoordinate_stdGaussian (u : E) (hu : u ≠ 0) :
    Measure.map (gaussianAxisCoordinate u) (stdGaussian E) =
      gaussianReal 0 1 := by
  let L : StrongDual ℝ E := ‖u‖⁻¹ • innerSL ℝ u
  have hL : (L : E → ℝ) = gaussianAxisCoordinate u := by
    funext v
    simp [L, gaussianAxisCoordinate, div_eq_mul_inv, mul_comm]
  rw [← hL, IsGaussian.map_eq_gaussianReal,
    integral_strongDual_stdGaussian, variance_dual_stdGaussian]
  have hnormu : ‖u‖ ≠ 0 := norm_ne_zero_iff.mpr hu
  have hnormL : ‖L‖ = 1 := by
    rw [show L = ‖u‖⁻¹ • innerSL ℝ u by rfl, norm_smul,
      innerSL_apply_norm, Real.norm_eq_abs, abs_inv, abs_norm,
      inv_mul_cancel₀ hnormu]
  rw [hnormL]
  norm_num

/-- For a fixed nonzero axis in dimension `m ≥ 2`, the signed axial
coordinate and the orthogonal residual energy are independent, with exact
`N(0,1)` and `Gamma((m-1)/2,1/2)` laws. -/
theorem hasLaw_gaussianAxisCoordinates_stdGaussian_fixed
    (m : ℕ) (hdim : finrank ℝ E = m) (hm : 2 ≤ m)
    (u : E) (hu : u ≠ 0) :
    HasLaw (gaussianAxisCoordinates u)
      ((gaussianReal 0 1).prod
        (gammaMeasure (((m - 1 : ℕ) : ℝ) / 2) (1 / 2)))
      (stdGaussian E) := by
  let K : Submodule ℝ E := ℝ ∙ u
  have hfinK : finrank ℝ K = 1 := by
    simpa [K] using finrank_span_singleton hu
  have hfinPerp : finrank ℝ K.orthogonal = m - 1 := by
    have hadd := K.finrank_add_finrank_orthogonal
    rw [hfinK, hdim] at hadd
    omega
  let _ : Nontrivial K.orthogonal :=
    Module.nontrivial_of_finrank_pos
      (by omega : 0 < finrank ℝ K.orthogonal)
  have hcoordinate : HasLaw (gaussianAxisCoordinate u)
      (gaussianReal 0 1) (stdGaussian E) :=
    ⟨(measurable_gaussianAxisCoordinate u).aemeasurable,
      map_gaussianAxisCoordinate_stdGaussian u hu⟩
  have hresidualProjection :=
    hasLaw_normSq_orthogonalComplementProjection_gamma K
  have hresidual : HasLaw (gaussianAxisResidualEnergy u)
      (gammaMeasure (((m - 1 : ℕ) : ℝ) / 2) (1 / 2))
      (stdGaussian E) := by
    rw [hfinPerp] at hresidualProjection
    exact hresidualProjection.congr
      (Filter.Eventually.of_forall fun v ↦
        gaussianAxisResidualEnergy_eq_orthogonalProjection u v hu)
  let phi : K → ℝ := fun q ↦ gaussianAxisCoordinate u (q : E)
  let psi : K.orthogonal → ℝ := fun q ↦ ‖q‖ ^ 2
  have hindepProjection := indepFun_orthogonalProjections_stdGaussian K
  have hindepComposed := hindepProjection.comp
    (φ := phi) (ψ := psi)
    ((measurable_gaussianAxisCoordinate u).comp measurable_subtype_coe)
    (by fun_prop)
  have hleft :
      (phi ∘ K.orthogonalProjectionOnto) =ᵐ[stdGaussian E]
        gaussianAxisCoordinate u := by
    filter_upwards [] with v
    unfold phi gaussianAxisCoordinate
    change inner ℝ u (K.orthogonalProjectionOnto v : E) / ‖u‖ =
      inner ℝ u v / ‖u‖
    have hi := K.inner_orthogonalProjectionOnto_eq_of_mem_left
      (⟨u, Submodule.mem_span_singleton_self u⟩ : K) v
    have hi' : inner ℝ u (K.orthogonalProjectionOnto v : E) =
        inner ℝ u v := by
      simpa only [K.coe_inner] using hi
    rw [hi']
  have hright :
      (psi ∘ K.orthogonal.orthogonalProjectionOnto) =ᵐ[stdGaussian E]
        gaussianAxisResidualEnergy u := by
    filter_upwards [] with v
    exact (gaussianAxisResidualEnergy_eq_orthogonalProjection u v hu).symm
  have hindep : IndepFun (gaussianAxisCoordinate u)
      (gaussianAxisResidualEnergy u) (stdGaussian E) :=
    hindepComposed.congr hleft hright
  change HasLaw
    (fun v ↦ (gaussianAxisCoordinate u v, gaussianAxisResidualEnergy u v))
      ((gaussianReal 0 1).prod
        (gammaMeasure (((m - 1 : ℕ) : ℝ) / 2) (1 / 2)))
      (stdGaussian E)
  exact hindep.hasLaw_prod hcoordinate hresidual

/-- Keep the random Gaussian axis together with its two coordinates for an
independent second Gaussian vector. -/
def retainFirstAndGaussianAxisCoordinates (z : E × E) :
    E × (ℝ × ℝ) :=
  (z.1, gaussianAxisCoordinates z.1 z.2)

theorem measurable_retainFirstAndGaussianAxisCoordinates :
    Measurable (retainFirstAndGaussianAxisCoordinates (E := E)) := by
  exact measurable_fst.prodMk measurable_uncurry_gaussianAxisCoordinates

/-- Exact random-axis product law.  The first Gaussian vector is independent
of the standard-normal axial coordinate and the orthogonal chi-square
energy of a fresh Gaussian vector. -/
theorem map_retainFirstAndGaussianAxisCoordinates_gaussianProduct
    (m : ℕ) (hdim : finrank ℝ E = m) (hm : 2 ≤ m) :
    Measure.map (retainFirstAndGaussianAxisCoordinates (E := E))
        ((stdGaussian E).prod (stdGaussian E)) =
      (stdGaussian E).prod
        ((gaussianReal 0 1).prod
          (gammaMeasure (((m - 1 : ℕ) : ℝ) / 2) (1 / 2))) := by
  let _ : Nontrivial E :=
    Module.nontrivial_of_finrank_pos (by omega : 0 < finrank ℝ E)
  have hnonzero : ∀ᵐ u ∂stdGaussian E, u ≠ 0 := by
    simpa [ae_iff] using stdGaussian_zero_singleton (E := E)
  have hlaw : ∀ᵐ u ∂stdGaussian E,
      Measure.map (gaussianAxisCoordinates u) (stdGaussian E) =
        (gaussianReal 0 1).prod
          (gammaMeasure (((m - 1 : ℕ) : ℝ) / 2) (1 / 2)) := by
    filter_upwards [hnonzero] with u hu
    exact (hasLaw_gaussianAxisCoordinates_stdGaussian_fixed
      m hdim hm u hu).map_eq
  exact ((MeasurePreserving.id (stdGaussian E)).skew_product
    measurable_uncurry_gaussianAxisCoordinates hlaw).map_eq

/-- A standard Gaussian norm has the chi law defined above. -/
theorem map_norm_stdGaussian_eq_chiMeasure
    (m : ℕ) [Nontrivial E] (hdim : finrank ℝ E = m) :
    Measure.map norm (stdGaussian E) = chiMeasure m := by
  unfold chiMeasure
  rw [← hdim, ← stdGaussianNormSqMeasure_eq_gamma E]
  unfold stdGaussianNormSqMeasure
  rw [Measure.map_map (by fun_prop) (by fun_prop)]
  apply Measure.map_congr
  filter_upwards [] with v
  simp

/-- The norm, signed axial coordinate, and orthogonal energy. -/
def gaussianRubenCoordinates (z : E × E) : ℝ × (ℝ × ℝ) :=
  (‖z.1‖, gaussianAxisCoordinates z.1 z.2)

theorem measurable_gaussianRubenCoordinates :
    Measurable (gaussianRubenCoordinates (E := E)) := by
  exact measurable_fst.norm.prodMk measurable_uncurry_gaussianAxisCoordinates

/-- Exact three-coordinate version: for independent standard Gaussian
vectors `x,e`, the variables
`(‖x‖, ⟨x,e⟩/‖x‖, ‖e‖²-(⟨x,e⟩/‖x‖)²)` are mutually independent
with chi, standard-normal, and chi-square/Gamma laws. -/
theorem map_gaussianRubenCoordinates_gaussianProduct
    (m : ℕ) (hdim : finrank ℝ E = m) (hm : 2 ≤ m) :
    Measure.map (gaussianRubenCoordinates (E := E))
        ((stdGaussian E).prod (stdGaussian E)) =
      (chiMeasure m).prod
        ((gaussianReal 0 1).prod
          (gammaMeasure (((m - 1 : ℕ) : ℝ) / 2) (1 / 2))) := by
  let _ : Nontrivial E :=
    Module.nontrivial_of_finrank_pos (by omega : 0 < finrank ℝ E)
  have hnonzero : ∀ᵐ u ∂stdGaussian E, u ≠ 0 := by
    simpa [ae_iff] using stdGaussian_zero_singleton (E := E)
  have hlaw : ∀ᵐ u ∂stdGaussian E,
      Measure.map (gaussianAxisCoordinates u) (stdGaussian E) =
        (gaussianReal 0 1).prod
          (gammaMeasure (((m - 1 : ℕ) : ℝ) / 2) (1 / 2)) := by
    filter_upwards [hnonzero] with u hu
    exact (hasLaw_gaussianAxisCoordinates_stdGaussian_fixed
      m hdim hm u hu).map_eq
  have hnorm : MeasurePreserving (fun u : E ↦ ‖u‖)
      (stdGaussian E) (chiMeasure m) :=
    ⟨by fun_prop, map_norm_stdGaussian_eq_chiMeasure m hdim⟩
  exact (hnorm.skew_product
    measurable_uncurry_gaussianAxisCoordinates hlaw).map_eq

end

end LogdetLean.Coherence
