import Mathlib.Analysis.Calculus.ContDiff.Deriv
import Mathlib.Analysis.Calculus.MeanValue
import Mathlib.Analysis.SpecialFunctions.ExpDeriv
import Mathlib.MeasureTheory.Integral.IntervalIntegral.FundThmCalculus
import Mathlib.Tactic

/-!
# A global logarithm for a nonvanishing differentiable curve

For a differentiable complex-valued curve satisfying `F' = g F` and
`F(0)=1`, the real path integral of `g` is a global additive logarithm:

`exp (integral_0^t g) = F(t)`.

This elementary ODE construction avoids choosing a principal logarithm of
the values of `F`.  It is useful for characteristic functions that are
nonzero on the real frequency axis but may cross the negative real axis.
-/

namespace LogdetLean

noncomputable section

open MeasureTheory Set

/-- The path-integral logarithm generated by a continuous logarithmic
derivative. -/
def curveLogIntegral (g : ℝ → ℂ) (t : ℝ) : ℂ :=
  ∫ x in (0 : ℝ)..t, g x

/-- The path-integral logarithm has derivative `g`. -/
theorem hasDerivAt_curveLogIntegral {g : ℝ → ℂ}
    (hg : Continuous g) (t : ℝ) :
    HasDerivAt (curveLogIntegral g) (g t) t := by
  unfold curveLogIntegral
  exact intervalIntegral.integral_hasDerivAt_right
    (hg.intervalIntegrable 0 t)
    hg.aestronglyMeasurable.stronglyMeasurableAtFilter hg.continuousAt

/-- If `g` is twice continuously differentiable, its path integral is three
times continuously differentiable. -/
theorem contDiff_three_curveLogIntegral {g : ℝ → ℂ}
    (hg : ContDiff ℝ 2 g) :
    ContDiff ℝ 3 (curveLogIntegral g) := by
  have hdiff : Differentiable ℝ (curveLogIntegral g) := fun t ↦
    (hasDerivAt_curveLogIntegral hg.continuous t).differentiableAt
  have hderiv : deriv (curveLogIntegral g) = g := by
    funext t
    exact (hasDerivAt_curveLogIntegral hg.continuous t).deriv
  apply (contDiff_succ_iff_deriv (n := 2)).2
  exact ⟨hdiff, by simp, by simpa [hderiv] using hg⟩

/-- The path integral is the global additive logarithm of any normalized
solution of `F'=gF`.  No branch-cut hypothesis is needed. -/
theorem cexp_curveLogIntegral_eq
    {F g : ℝ → ℂ}
    (hg : Continuous g)
    (hF : ∀ t, HasDerivAt F (g t * F t) t)
    (hFzero : F 0 = 1) (t : ℝ) :
    Complex.exp (curveLogIntegral g t) = F t := by
  let H : ℝ → ℂ := fun x ↦
    Complex.exp (-curveLogIntegral g x) * F x
  have hH : ∀ x, HasDerivAt H 0 x := by
    intro x
    have hlog := hasDerivAt_curveLogIntegral hg x
    have hexp := hlog.neg.cexp
    have hprod := hexp.mul (hF x)
    apply hprod.congr_deriv
    dsimp [H]
    ring
  have hHdiff : Differentiable ℝ H := fun x ↦ (hH x).differentiableAt
  have hconstdiff : Differentiable ℝ (fun _ : ℝ ↦ (1 : ℂ)) :=
    differentiable_const 1
  have hderivEq : Set.univ.EqOn (deriv H)
      (deriv (fun _ : ℝ ↦ (1 : ℂ))) := by
    intro x _hx
    rw [(hH x).deriv]
    simp
  have hHzero : H 0 = 1 := by
    simp [H, curveLogIntegral, hFzero]
  have hall : Set.univ.EqOn H (fun _ : ℝ ↦ (1 : ℂ)) :=
    isOpen_univ.eqOn_of_deriv_eq isPreconnected_univ
      hHdiff.differentiableOn hconstdiff.differentiableOn
      hderivEq (by simp) hHzero
  have hHt : H t = 1 := by simpa using hall (Set.mem_univ t)
  calc
    Complex.exp (curveLogIntegral g t) =
        Complex.exp (curveLogIntegral g t) * 1 := by ring
    _ = Complex.exp (curveLogIntegral g t) *
        (Complex.exp (-curveLogIntegral g t) * F t) := by
      rw [show Complex.exp (-curveLogIntegral g t) * F t = 1 by
        simpa [H] using hHt]
    _ = F t := by
      rw [← mul_assoc, ← Complex.exp_add]
      simp

end

end LogdetLean
