import A2.SpectrumInvariant
import A2.SpectrumPositivity

#print axioms A2Research.exists_perm_of_multiset_map_univ_eq
#print axioms A2Research.charpoly_eq_realRootPolynomial_eigenvalues
#print axioms A2Research.eigenvalues_permutation_of_charpoly_eq
#print axioms A2Research.charpoly_unitary_conjugation
#print axioms A2Research.eigenvalues_permutation_of_unitary_diagonalization
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.canonicalGapSquaredSpectrum_permutation_of_gap_diagonalization
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.coeHermitianGap_diagonalization_of_unitary_congruence
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.canonicalGapSquaredSpectrum_permutation_of_unitary_congruence
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.canonicalGapSquaredSpectrum_permutation_of_sqrt_unitary_congruence
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.permutationInvariantSpectralTest_eq_of_unitary_congruence
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.permutationInvariantSpectralTest_eq_of_sqrt_unitary_congruence
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.canonicalGapSquaredSpectrum_mem_gram_spectrum
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.canonicalGapSquaredSpectrum_nonneg
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.canonicalGapSquaredSpectrum_pos_of_det_ne_zero
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.canonicalGapSquaredSpectrum_mem_openPositiveOrthant_of_det_ne_zero
