import LogdetLean.GramHafnian.UltimateHiding.DenseLocalStep.TaylorTV
import LogdetLean.GramHafnian.UltimateHiding.Dense.BetaTailConcrete
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.Tactic

/-!
# Scalar--orbital one-step bridge

This file isolates the generic analytic bookkeeping in the dense one-column
argument.  It proves the scalar Duhamel estimate with the *mean scalar
increment retained before taking absolute values*, the centered orbital
Taylor estimate, their exact TV composition, and the final reciprocal-product
rate algebra.

There is no Haar, COE, Wishart, score, or beta axiom here.  A concrete use must
supply the event paths, their score bounds, the scalar and orbital moment
bounds, and the exceptional-event TV contribution as explicit hypotheses.
-/

open MeasureTheory Set

namespace LogdetLean.GramHafnian.UltimateHiding.DenseLocalStep

noncomputable section

/-! ## The exact beta-log moment interface -/

/-- The scalar Taylor budget generated by the central score bounds
`C₁ N` and `C₂ N²`. -/
def oneColumnScalarTaylorBudget
    (CscoreOne CscoreTwo : ℝ) (m N : ℕ) : ℝ :=
  CscoreOne * (N : ℝ) *
      |∫ q, Dense.oneColumnCenteredScalarLog m N q
        ∂(Dense.oneColumnBetaLaw m N)| +
    CscoreTwo * (N : ℝ) ^ 2 *
      (∫ q, Dense.oneColumnCenteredScalarLog m N q ^ 2
        ∂(Dense.oneColumnBetaLaw m N)) / 2

/-- The centered orbital Taylor budget generated by the score bounds
`C₂` and `C₃ N`. -/
def oneColumnOrbitalTaylorBudget
    (CorbitalTwo CorbitalThree : ℝ) (m N : ℕ) : ℝ :=
  CorbitalTwo *
      (∫ q, Dense.oneColumnRankOneLog q ^ 2
        ∂(Dense.oneColumnBetaLaw m N)) / 2 +
    CorbitalThree * (N : ℝ) *
      (∫ q, |Dense.oneColumnRankOneLog q| ^ 3
        ∂(Dense.oneColumnBetaLaw m N)) / 6

/-- The four beta-log estimates still required by the dense local proof,
normalized at the squared hiding scale.

The first inequality retains the signed mean before taking its absolute
value.  The last inequality is the large-ambient form of
`E|b_m|³ = O(N³/m³)` after using `m >= N²`; it is deliberately exposed
rather than silently folded into a generic constant. -/
structure OneColumnLogMomentBoundsAt
    (Cmean CscalarTwo CbTwo CbThree : ℝ) (m N : ℕ) : Prop where
  Cmean_nonneg : 0 ≤ Cmean
  CscalarTwo_nonneg : 0 ≤ CscalarTwo
  CbTwo_nonneg : 0 ≤ CbTwo
  CbThree_nonneg : 0 ≤ CbThree
  centeredScalar_integrable :
    Integrable (Dense.oneColumnCenteredScalarLog m N)
      (Dense.oneColumnBetaLaw m N)
  centeredScalar_sq_integrable :
    Integrable (fun q ↦ Dense.oneColumnCenteredScalarLog m N q ^ 2)
      (Dense.oneColumnBetaLaw m N)
  rankOne_sq_integrable :
    Integrable (fun q ↦ Dense.oneColumnRankOneLog q ^ 2)
      (Dense.oneColumnBetaLaw m N)
  rankOne_cube_integrable :
    Integrable (fun q ↦ |Dense.oneColumnRankOneLog q| ^ 3)
      (Dense.oneColumnBetaLaw m N)
  centeredScalar_mean_le :
    |∫ q, Dense.oneColumnCenteredScalarLog m N q
        ∂(Dense.oneColumnBetaLaw m N)| ≤
      Cmean * (N : ℝ) /
        ((m : ℝ) * ((m + 1 : ℕ) : ℝ))
  centeredScalar_second_le :
    (∫ q, Dense.oneColumnCenteredScalarLog m N q ^ 2
        ∂(Dense.oneColumnBetaLaw m N)) ≤
      2 * CscalarTwo /
        ((m : ℝ) * ((m + 1 : ℕ) : ℝ))
  rankOne_second_le :
    (∫ q, Dense.oneColumnRankOneLog q ^ 2
        ∂(Dense.oneColumnBetaLaw m N)) ≤
      CbTwo * (N : ℝ) ^ 2 /
        ((m : ℝ) * ((m + 1 : ℕ) : ℝ))
  rankOne_third_le :
    (∫ q, |Dense.oneColumnRankOneLog q| ^ 3
        ∂(Dense.oneColumnBetaLaw m N)) ≤
      CbThree * (N : ℝ) /
        ((m : ℝ) * ((m + 1 : ℕ) : ℝ))

/-- The beta-log estimates and the scalar score bounds imply a scalar
one-step budget with the canonical reciprocal-product denominator. -/
theorem oneColumnScalarTaylorBudget_le
    {Cmean CscalarTwo CbTwo CbThree CscoreOne CscoreTwo : ℝ}
    {m N : ℕ}
    (hmom : OneColumnLogMomentBoundsAt
      Cmean CscalarTwo CbTwo CbThree m N)
    (hscoreOne : 0 ≤ CscoreOne) (hscoreTwo : 0 ≤ CscoreTwo) :
    oneColumnScalarTaylorBudget CscoreOne CscoreTwo m N ≤
      (CscoreOne * Cmean + CscoreTwo * CscalarTwo) *
        (N : ℝ) ^ 2 /
          ((m : ℝ) * ((m + 1 : ℕ) : ℝ)) := by
  have hNnonneg : 0 ≤ (N : ℝ) := Nat.cast_nonneg N
  have hNtwo : 0 ≤ (N : ℝ) ^ 2 := sq_nonneg _
  have hfirst := mul_le_mul_of_nonneg_left hmom.centeredScalar_mean_le
    (mul_nonneg hscoreOne hNnonneg)
  have hsecond := mul_le_mul_of_nonneg_left hmom.centeredScalar_second_le
    (mul_nonneg hscoreTwo hNtwo)
  unfold oneColumnScalarTaylorBudget
  calc
    CscoreOne * (N : ℝ) *
          |∫ q, Dense.oneColumnCenteredScalarLog m N q
            ∂(Dense.oneColumnBetaLaw m N)| +
        CscoreTwo * (N : ℝ) ^ 2 *
          (∫ q, Dense.oneColumnCenteredScalarLog m N q ^ 2
            ∂(Dense.oneColumnBetaLaw m N)) / 2 ≤
      CscoreOne * (N : ℝ) *
          (Cmean * (N : ℝ) /
            ((m : ℝ) * ((m + 1 : ℕ) : ℝ))) +
        (CscoreTwo * (N : ℝ) ^ 2) *
          (2 * CscalarTwo /
            ((m : ℝ) * ((m + 1 : ℕ) : ℝ))) / 2 := by
        exact add_le_add hfirst (div_le_div_of_nonneg_right hsecond (by norm_num))
    _ = (CscoreOne * Cmean + CscoreTwo * CscalarTwo) *
        (N : ℝ) ^ 2 /
          ((m : ℝ) * ((m + 1 : ℕ) : ℝ)) := by ring

/-- The beta-log estimates and centered orbital score bounds imply the
orbital one-step budget with the same denominator. -/
theorem oneColumnOrbitalTaylorBudget_le
    {Cmean CscalarTwo CbTwo CbThree CorbitalTwo CorbitalThree : ℝ}
    {m N : ℕ}
    (hmom : OneColumnLogMomentBoundsAt
      Cmean CscalarTwo CbTwo CbThree m N)
    (horbitalTwo : 0 ≤ CorbitalTwo)
    (horbitalThree : 0 ≤ CorbitalThree) :
    oneColumnOrbitalTaylorBudget CorbitalTwo CorbitalThree m N ≤
      (CorbitalTwo * CbTwo / 2 + CorbitalThree * CbThree / 6) *
        (N : ℝ) ^ 2 /
          ((m : ℝ) * ((m + 1 : ℕ) : ℝ)) := by
  have hNnonneg : 0 ≤ (N : ℝ) := Nat.cast_nonneg N
  have hsecond := mul_le_mul_of_nonneg_left hmom.rankOne_second_le
    horbitalTwo
  have hthird := mul_le_mul_of_nonneg_left hmom.rankOne_third_le
    (mul_nonneg horbitalThree hNnonneg)
  unfold oneColumnOrbitalTaylorBudget
  calc
    CorbitalTwo *
          (∫ q, Dense.oneColumnRankOneLog q ^ 2
            ∂(Dense.oneColumnBetaLaw m N)) / 2 +
        CorbitalThree * (N : ℝ) *
          (∫ q, |Dense.oneColumnRankOneLog q| ^ 3
            ∂(Dense.oneColumnBetaLaw m N)) / 6 ≤
      CorbitalTwo *
          (CbTwo * (N : ℝ) ^ 2 /
            ((m : ℝ) * ((m + 1 : ℕ) : ℝ))) / 2 +
        (CorbitalThree * (N : ℝ)) *
          (CbThree * (N : ℝ) /
            ((m : ℝ) * ((m + 1 : ℕ) : ℝ))) / 6 := by
        exact add_le_add
          (div_le_div_of_nonneg_right hsecond (by norm_num))
          (div_le_div_of_nonneg_right hthird (by norm_num))
    _ = (CorbitalTwo * CbTwo / 2 + CorbitalThree * CbThree / 6) *
        (N : ℝ) ^ 2 /
          ((m : ℝ) * ((m + 1 : ℕ) : ℝ)) := by ring

/-! ## Exact scalar--orbital TV composition -/

/-- Central and orbital errors add by the eventwise total-variation triangle
inequality.  This is the formal form of the exact operator split
`e^(cX) K_b - I = (e^(cX)-I) + e^(cX)(K_b-I)`: the latter identity and TV
isometry are precisely what a concrete construction must use to provide the
two hypotheses below. -/
theorem probabilityTVLE_of_scalar_orbital_split
    {State : Type*} [MeasurableSpace State]
    (mu scalarLaw nu : Measure State)
    {scalarBudget orbitalBudget : ℝ}
    (hscalar : Dense.ProbabilityTVLE mu scalarLaw scalarBudget)
    (horbital : Dense.ProbabilityTVLE scalarLaw nu orbitalBudget) :
    Dense.ProbabilityTVLE mu nu (scalarBudget + orbitalBudget) :=
  Dense.probabilityTVLE_triangle hscalar horbital

/-- Adding an explicitly exposed exceptional-event budget. -/
theorem probabilityTVLE_of_scalar_orbital_good_bad
    {State : Type*} [MeasurableSpace State]
    (mu scalarLaw goodLaw nu : Measure State)
    {scalarBudget orbitalGoodBudget badBudget : ℝ}
    (hscalar : Dense.ProbabilityTVLE mu scalarLaw scalarBudget)
    (horbitalGood :
      Dense.ProbabilityTVLE scalarLaw goodLaw orbitalGoodBudget)
    (hbad : Dense.ProbabilityTVLE goodLaw nu badBudget) :
    Dense.ProbabilityTVLE mu nu
      (scalarBudget + orbitalGoodBudget + badBudget) := by
  exact Dense.probabilityTVLE_triangle
    (Dense.probabilityTVLE_triangle hscalar horbitalGood) hbad

/-- The already proved concrete beta tail supplies the bad-event term in the
same reciprocal-product normalization as the smooth Taylor terms.  The only
hypothesis here is the concrete coupling/mixture statement saying that
discarding the bad beta event costs at most its probability. -/
theorem probabilityTVLE_badEvent_to_denseTelescopingRate
    {State : Type*} [MeasurableSpace State]
    (goodLaw fullLaw : Measure State) {m N : ℕ}
    (hN : 1 ≤ N) (hNm : N ≤ m)
    (hthreshold : 24 * (N : ℝ) ^ 2 ≤ (m : ℝ))
    (hbad : Dense.ProbabilityTVLE goodLaw fullLaw
      (Dense.oneColumnLogBadProbability m N 1)) :
    Dense.ProbabilityTVLE goodLaw fullLaw
      (Dense.denseTelescopingRate 72 N m) :=
  hbad.mono
    (Dense.oneColumnLogBadProbability_le_telescopingRate_concrete
      hN hNm hthreshold)

/-! ## Reciprocal-product rate closure -/

/-- Pure numerical closure of the one-step argument.

Every analytic input is visible as one of `hscalar`, `horbital`, or `hbad`.
The mild extra factor `(m+1)/m` is absorbed without changing the canonical
telescoping denominator. -/
theorem sum_three_denseTelescopingRate_le
    (Cscalar Corbital Cbad C : ℝ) (N m : ℕ)
    (hm : 1 ≤ m) (hC : Cscalar + Corbital + Cbad ≤ C) :
    Cscalar * (N : ℝ) ^ 2 /
          ((m : ℝ) * ((m + 1 : ℕ) : ℝ)) +
        Corbital * (N : ℝ) ^ 2 /
          ((m : ℝ) * ((m + 1 : ℕ) : ℝ)) +
        Cbad * (N : ℝ) ^ 2 /
          ((m : ℝ) * ((m + 1 : ℕ) : ℝ)) ≤
      Dense.denseTelescopingRate C N m := by
  have hrate : 0 ≤ (N : ℝ) ^ 2 /
      ((m : ℝ) * ((m + 1 : ℕ) : ℝ)) := by positivity
  have hmul := mul_le_mul_of_nonneg_right hC hrate
  calc
    Cscalar * (N : ℝ) ^ 2 /
          ((m : ℝ) * ((m + 1 : ℕ) : ℝ)) +
        Corbital * (N : ℝ) ^ 2 /
          ((m : ℝ) * ((m + 1 : ℕ) : ℝ)) +
        Cbad * (N : ℝ) ^ 2 /
          ((m : ℝ) * ((m + 1 : ℕ) : ℝ)) =
        (Cscalar + Corbital + Cbad) *
          ((N : ℝ) ^ 2 /
            ((m : ℝ) * ((m + 1 : ℕ) : ℝ))) := by ring
    _ ≤ C * ((N : ℝ) ^ 2 /
          ((m : ℝ) * ((m + 1 : ℕ) : ℝ))) := hmul
    _ = Dense.denseTelescopingRate C N m := by
      simp only [Dense.denseTelescopingRate]
      ring

/-- Clean endpoint: once the scalar, good-orbital, and bad-event estimates
are each already expressed with the reciprocal-product denominator, their
sum is a valid dense one-step estimate. -/
theorem probabilityTVLE_denseOneStep_of_three_budgets
    {State : Type*} [MeasurableSpace State]
    (mu scalarLaw goodLaw nu : Measure State)
    (Cscalar Corbital Cbad C : ℝ) (N m : ℕ)
    (hm : 1 ≤ m)
    (hscalarTV : Dense.ProbabilityTVLE mu scalarLaw
      (Cscalar * (N : ℝ) ^ 2 /
        ((m : ℝ) * ((m + 1 : ℕ) : ℝ))))
    (horbitalTV : Dense.ProbabilityTVLE scalarLaw goodLaw
      (Corbital * (N : ℝ) ^ 2 /
        ((m : ℝ) * ((m + 1 : ℕ) : ℝ))))
    (hbadTV : Dense.ProbabilityTVLE goodLaw nu
      (Cbad * (N : ℝ) ^ 2 /
        ((m : ℝ) * ((m + 1 : ℕ) : ℝ))))
    (hC : Cscalar + Corbital + Cbad ≤ C) :
    Dense.ProbabilityTVLE mu nu (Dense.denseTelescopingRate C N m) := by
  have hraw := probabilityTVLE_of_scalar_orbital_good_bad
    mu scalarLaw goodLaw nu hscalarTV horbitalTV hbadTV
  exact hraw.mono (sum_three_denseTelescopingRate_le
    Cscalar Corbital Cbad C N m hm hC)

/-- Full generic dense one-step closure.

The hypotheses separate the remaining mathematical obligations exactly:

* `hmom` is beta log calculus (signed scalar mean and three moments);
* `hscalarTV` is the scalar event-path Duhamel estimate with score norms
  `CscoreOne*N` and `CscoreTwo*N²`;
* `horbitalTV` is the isotropically centered orbital Taylor estimate with
  score norms `CorbitalTwo` and `CorbitalThree*N`;
* `hbadTV` is the elementary good/bad coupling inequality.

Everything after those inputs, including the concrete beta-tail constant 72
and the exact `m(m+1)` denominator, is kernel checked here. -/
theorem probabilityTVLE_denseOneStep_of_betaLogScores
    {State : Type*} [MeasurableSpace State]
    (mu scalarLaw goodLaw nu : Measure State)
    {Cmean CscalarTwo CbTwo CbThree : ℝ}
    {CscoreOne CscoreTwo CorbitalTwo CorbitalThree : ℝ}
    {m N : ℕ}
    (hN : 1 ≤ N) (hNm : N ≤ m)
    (hthreshold : 24 * (N : ℝ) ^ 2 ≤ (m : ℝ))
    (hmom : OneColumnLogMomentBoundsAt
      Cmean CscalarTwo CbTwo CbThree m N)
    (hscoreOne : 0 ≤ CscoreOne) (hscoreTwo : 0 ≤ CscoreTwo)
    (horbitalTwo : 0 ≤ CorbitalTwo)
    (horbitalThree : 0 ≤ CorbitalThree)
    (hscalarTV : Dense.ProbabilityTVLE mu scalarLaw
      (oneColumnScalarTaylorBudget CscoreOne CscoreTwo m N))
    (horbitalTV : Dense.ProbabilityTVLE scalarLaw goodLaw
      (oneColumnOrbitalTaylorBudget CorbitalTwo CorbitalThree m N))
    (hbadTV : Dense.ProbabilityTVLE goodLaw nu
      (Dense.oneColumnLogBadProbability m N 1)) :
    Dense.ProbabilityTVLE mu nu
      (Dense.denseTelescopingRate
        (CscoreOne * Cmean + CscoreTwo * CscalarTwo +
          (CorbitalTwo * CbTwo / 2 + CorbitalThree * CbThree / 6) + 72)
        N m) := by
  let Cscalar : ℝ := CscoreOne * Cmean + CscoreTwo * CscalarTwo
  let Corbital : ℝ :=
    CorbitalTwo * CbTwo / 2 + CorbitalThree * CbThree / 6
  have hscalarRate : Dense.ProbabilityTVLE mu scalarLaw
      (Cscalar * (N : ℝ) ^ 2 /
        ((m : ℝ) * ((m + 1 : ℕ) : ℝ))) :=
    hscalarTV.mono (by
      dsimp only [Cscalar]
      exact oneColumnScalarTaylorBudget_le hmom hscoreOne hscoreTwo)
  have horbitalRate : Dense.ProbabilityTVLE scalarLaw goodLaw
      (Corbital * (N : ℝ) ^ 2 /
        ((m : ℝ) * ((m + 1 : ℕ) : ℝ))) :=
    horbitalTV.mono (by
      dsimp only [Corbital]
      exact oneColumnOrbitalTaylorBudget_le hmom horbitalTwo horbitalThree)
  have hbadRate := probabilityTVLE_badEvent_to_denseTelescopingRate
    goodLaw nu hN hNm hthreshold hbadTV
  have hclosed := probabilityTVLE_denseOneStep_of_three_budgets
    mu scalarLaw goodLaw nu Cscalar Corbital 72
      (Cscalar + Corbital + 72) N m (hN.trans hNm)
      hscalarRate horbitalRate hbadRate (by rfl)
  simpa [Cscalar, Corbital, add_assoc] using hclosed

/-- Event-path form of the complete generic bridge.

This theorem begins with the literal scalar and orbital paths.  The hypothesis
`horbitalFirst` is the exact isotropic cancellation `K'_0 = 0`; the scalar
first derivative is not discarded, and is multiplied by the signed beta mean.
The `orbitalAmplitude` may be the beta logarithm truncated to the good event.
The two moment-comparison hypotheses then compare its moments with the full
beta moments, while `hbadTV` accounts for the discarded event. -/
theorem probabilityTVLE_denseOneStep_of_eventPaths
    {State : Type*} [MeasurableSpace State]
    (mu scalarLaw goodLaw nu : Measure State)
    {Cmean CscalarTwo CbTwo CbThree : ℝ}
    {CscoreOne CscoreTwo CorbitalTwo CorbitalThree : ℝ}
    {m N : ℕ}
    (hN : 1 ≤ N) (hNm : N ≤ m)
    (hthreshold : 24 * (N : ℝ) ^ 2 ≤ (m : ℝ))
    (hmom : OneColumnLogMomentBoundsAt
      Cmean CscalarTwo CbTwo CbThree m N)
    (hscoreOne : 0 ≤ CscoreOne) (hscoreTwo : 0 ≤ CscoreTwo)
    (horbitalTwo : 0 ≤ CorbitalTwo)
    (horbitalThree : 0 ≤ CorbitalThree)
    (scalarEventPath orbitalEventPath : Set State → ℝ → ℝ)
    (orbitalAmplitude : ℝ → ℝ)
    (hscalarMu : ∀ A, MeasurableSet A → scalarEventPath A 0 = mu.real A)
    (hscalarLaw : ∀ A, MeasurableSet A →
      ∫ q, scalarEventPath A (Dense.oneColumnCenteredScalarLog m N q)
        ∂(Dense.oneColumnBetaLaw m N) = scalarLaw.real A)
    (hscalarSmooth : ∀ A, MeasurableSet A → ContDiff ℝ 2 (scalarEventPath A))
    (hscalarFirst : ∀ A, MeasurableSet A →
      |iteratedDeriv 1 (scalarEventPath A) 0| ≤ CscoreOne * (N : ℝ))
    (hscalarSecond : ∀ A, MeasurableSet A → ∀ q,
      ∀ y ∈ uIcc 0 (Dense.oneColumnCenteredScalarLog m N q),
        |iteratedDeriv 2 (scalarEventPath A) y| ≤
          CscoreTwo * (N : ℝ) ^ 2)
    (hscalarPathIntegrable : ∀ A, MeasurableSet A →
      Integrable
        (fun q ↦ scalarEventPath A (Dense.oneColumnCenteredScalarLog m N q))
        (Dense.oneColumnBetaLaw m N))
    (horbitalMu : ∀ A, MeasurableSet A →
      orbitalEventPath A 0 = scalarLaw.real A)
    (horbitalLaw : ∀ A, MeasurableSet A →
      ∫ q, orbitalEventPath A (orbitalAmplitude q)
        ∂(Dense.oneColumnBetaLaw m N) = goodLaw.real A)
    (horbitalSmooth : ∀ A, MeasurableSet A →
      ContDiff ℝ 3 (orbitalEventPath A))
    (horbitalFirst : ∀ A, MeasurableSet A →
      iteratedDeriv 1 (orbitalEventPath A) 0 = 0)
    (horbitalSecond : ∀ A, MeasurableSet A →
      |iteratedDeriv 2 (orbitalEventPath A) 0| ≤ CorbitalTwo)
    (horbitalThird : ∀ A, MeasurableSet A → ∀ q,
      ∀ y ∈ uIcc 0 (orbitalAmplitude q),
        |iteratedDeriv 3 (orbitalEventPath A) y| ≤
          CorbitalThree * (N : ℝ))
    (horbitalPathIntegrable : ∀ A, MeasurableSet A →
      Integrable (fun q ↦ orbitalEventPath A (orbitalAmplitude q))
        (Dense.oneColumnBetaLaw m N))
    (horbitalAmplitude_sq_integrable :
      Integrable (fun q ↦ orbitalAmplitude q ^ 2)
        (Dense.oneColumnBetaLaw m N))
    (horbitalAmplitude_cube_integrable :
      Integrable (fun q ↦ |orbitalAmplitude q| ^ 3)
        (Dense.oneColumnBetaLaw m N))
    (horbitalSecondMoment_le :
      (∫ q, orbitalAmplitude q ^ 2 ∂(Dense.oneColumnBetaLaw m N)) ≤
        ∫ q, Dense.oneColumnRankOneLog q ^ 2
          ∂(Dense.oneColumnBetaLaw m N))
    (horbitalThirdMoment_le :
      (∫ q, |orbitalAmplitude q| ^ 3 ∂(Dense.oneColumnBetaLaw m N)) ≤
        ∫ q, |Dense.oneColumnRankOneLog q| ^ 3
          ∂(Dense.oneColumnBetaLaw m N))
    (hbadTV : Dense.ProbabilityTVLE goodLaw nu
      (Dense.oneColumnLogBadProbability m N 1)) :
    Dense.ProbabilityTVLE mu nu
      (Dense.denseTelescopingRate
        (CscoreOne * Cmean + CscoreTwo * CscalarTwo +
          (CorbitalTwo * CbTwo / 2 + CorbitalThree * CbThree / 6) + 72)
        N m) := by
  letI : IsProbabilityMeasure (Dense.oneColumnBetaLaw m N) :=
    Dense.oneColumnBetaLaw_isProbability hN hNm
  have hscalarTV : Dense.ProbabilityTVLE mu scalarLaw
      (oneColumnScalarTaylorBudget CscoreOne CscoreTwo m N) := by
    have hraw := probabilityTVLE_of_random_scalar_eventPath
      mu scalarLaw (Dense.oneColumnBetaLaw m N)
      (Dense.oneColumnCenteredScalarLog m N) scalarEventPath
      (CscoreOne * (N : ℝ)) (CscoreTwo * (N : ℝ) ^ 2)
      (mul_nonneg hscoreOne (Nat.cast_nonneg N))
      (mul_nonneg hscoreTwo (sq_nonneg _))
      hscalarMu hscalarLaw hscalarSmooth hscalarFirst hscalarSecond
      hscalarPathIntegrable hmom.centeredScalar_integrable
      hmom.centeredScalar_sq_integrable
    simpa [oneColumnScalarTaylorBudget] using hraw
  have horbitalRaw := probabilityTVLE_of_random_centered_eventPath
    scalarLaw goodLaw (Dense.oneColumnBetaLaw m N) orbitalAmplitude
      orbitalEventPath CorbitalTwo (CorbitalThree * (N : ℝ))
      horbitalTwo (mul_nonneg horbitalThree (Nat.cast_nonneg N))
      horbitalMu horbitalLaw horbitalSmooth horbitalFirst horbitalSecond
      horbitalThird horbitalPathIntegrable
      horbitalAmplitude_sq_integrable horbitalAmplitude_cube_integrable
  have horbitalBudgetLe :
      CorbitalTwo *
            (∫ q, orbitalAmplitude q ^ 2
              ∂(Dense.oneColumnBetaLaw m N)) / 2 +
          (CorbitalThree * (N : ℝ)) *
            (∫ q, |orbitalAmplitude q| ^ 3
              ∂(Dense.oneColumnBetaLaw m N)) / 6 ≤
        oneColumnOrbitalTaylorBudget CorbitalTwo CorbitalThree m N := by
    unfold oneColumnOrbitalTaylorBudget
    exact add_le_add
      (div_le_div_of_nonneg_right
        (mul_le_mul_of_nonneg_left horbitalSecondMoment_le horbitalTwo)
        (by norm_num))
      (div_le_div_of_nonneg_right
        (mul_le_mul_of_nonneg_left horbitalThirdMoment_le
          (mul_nonneg horbitalThree (Nat.cast_nonneg N)))
        (by norm_num))
  have horbitalTV : Dense.ProbabilityTVLE scalarLaw goodLaw
      (oneColumnOrbitalTaylorBudget CorbitalTwo CorbitalThree m N) :=
    horbitalRaw.mono horbitalBudgetLe
  exact probabilityTVLE_denseOneStep_of_betaLogScores
    mu scalarLaw goodLaw nu hN hNm hthreshold hmom
      hscoreOne hscoreTwo horbitalTwo horbitalThree
      hscalarTV horbitalTV hbadTV

end

end LogdetLean.GramHafnian.UltimateHiding.DenseLocalStep
