import LogdetLean.GramHafnian.UltimateHiding.DenseLocalStep.COEBaseRadialPropagation
import LogdetLean.GramHafnian.UltimateHiding.DenseScore.CenteredFlowGeometry
import LogdetLean.GramHafnian.UltimateHiding.DenseScore.QuadraticCenteringFromMass
import Mathlib.Tactic

/-!
# Identifying the shared-beta path with the centered COE path

This file proves the exact measure-theoretic bridge between the event path
used by the correlation-safe one-column Taylor argument and the canonical
projectively averaged centered COE event path used by the determinant-density
calculus.  The same beta sample remains fixed throughout; its scalar part
only changes the event by a measurable preimage.

There is no density, score, moment, total-variation, or hiding input here.
-/

open MeasureTheory ProbabilityTheory Set

namespace LogdetLean.GramHafnian.UltimateHiding.DenseLocalStep

noncomputable section

set_option maxHeartbeats 800000

open LogdetLean.GramHafnian.UltimateHiding
open LogdetLean.GramHafnian.UltimateHiding.Dense
open LogdetLean.GramHafnian.UltimateHiding.DenseScore

/-- Averaging the literal centered exponential flow over the complex unit
sphere is exactly the concrete orbital Markov action. -/
theorem concreteProjectiveAveragedCenteredCOEEventPath_eq_orbitalAction
    {N K : ℕ} (hN : 1 ≤ N) (hNK : N ≤ K)
    (event : Set (ConcreteMatrixState N)) (hevent : MeasurableSet event)
    (t : ℝ) :
    concreteProjectiveAveragedCenteredCOEEventPath N K event t =
      (concreteOrbitalMatrixKernel N t ∘ₘ
        concreteScaledCOECornerLaw
          CurrentPRL.canonicalUnitaryHaarProbabilityFamily N K).real event := by
  let mu := concreteScaledCOECornerLaw
    CurrentPRL.canonicalUnitaryHaarProbabilityFamily N K
  let sphere := complexUnitSphereProbabilityMeasure N
  let _ : IsProbabilityMeasure mu :=
    concreteScaledCOECornerLaw_isProbability
      CurrentPRL.canonicalUnitaryHaarProbabilityFamily hNK
  let _ : IsProbabilityMeasure sphere :=
    complexUnitSphereProbabilityMeasure_isProbability hN
  let F : ComplexUnitSphere N × ConcreteMatrixState N →
      ConcreteMatrixState N :=
    fun vA ↦ concreteOrbitalMatrixUpdate N t vA.1 vA.2
  let G : ConcreteMatrixState N × ComplexUnitSphere N →
      ConcreteMatrixState N :=
    fun Av ↦ concreteOrbitalMatrixUpdate N t Av.2 Av.1
  have hG : Measurable G := by
    exact measurable_concreteOrbitalMatrixUpdate N t
  have hF : Measurable F := by
    have hFG : F = G ∘ Prod.swap := by rfl
    rw [hFG]
    exact hG.comp measurable_swap
  have hsections := integral_map_sections_measureReal_eq_map_prod_measureReal
    sphere mu F hF event hevent
  have hswap : ((sphere.prod mu).map F).real event =
      ((mu.prod sphere).map G).real event := by
    have hmeasure : (sphere.prod mu).map F = (mu.prod sphere).map G := by
      rw [← Measure.prod_swap]
      rw [Measure.map_map hF measurable_swap]
      congr 1
    rw [hmeasure]
  have horbital :
      concreteOrbitalMatrixKernel N t ∘ₘ mu = (mu.prod sphere).map G := by
    unfold concreteOrbitalMatrixKernel
    exact independentUpdateKernel_comp_eq_map_prod mu sphere G hG
  unfold concreteProjectiveAveragedCenteredCOEEventPath
  change (∫ v : ComplexUnitSphere N,
      (Measure.map
        (transposeCongruenceFlow (concreteCenteredOrbitalDirection N v) t)
        mu).real event ∂sphere) = _
  have hflow (v : ComplexUnitSphere N) :
      (Measure.map
        (transposeCongruenceFlow (concreteCenteredOrbitalDirection N v) t)
        mu).real event =
      (mu.map (fun A ↦ concreteOrbitalMatrixUpdate N t v A)).real event := by
    congr 2
    funext A
    exact transposeCongruenceFlow_centered_eq_concreteOrbitalMatrixUpdate
      hN t v A
  calc
    (∫ v : ComplexUnitSphere N,
        (Measure.map
          (transposeCongruenceFlow (concreteCenteredOrbitalDirection N v) t)
          mu).real event ∂sphere) =
      (∫ v : ComplexUnitSphere N,
        (mu.map (fun A ↦ concreteOrbitalMatrixUpdate N t v A)).real event
        ∂sphere) := by
          apply integral_congr_ae
          filter_upwards [] with v
          exact hflow v
    _ = ((sphere.prod mu).map F).real event := hsections
    _ = ((mu.prod sphere).map G).real event := hswap
    _ = (concreteOrbitalMatrixKernel N t ∘ₘ mu).real event := by rw [horbital]

/-- At fixed beta sample `q`, the correlation-safe shared-beta orbital path
is the canonical projectively averaged centered COE path, evaluated on the
preimage of the event under the scalar congruence generated by that same
`q`. -/
theorem concreteSharedBetaOrbitalEventPath_eq_projectiveCenteredCOE
    {m N K : ℕ} (hN : 1 ≤ N) (hNK : N ≤ K)
    (q : ℝ) (event : Set (ConcreteMatrixState N))
    (hevent : MeasurableSet event) (t : ℝ) :
    concreteSharedBetaOrbitalEventPath m N
        (concreteScaledCOECornerLaw
          CurrentPRL.canonicalUnitaryHaarProbabilityFamily N K)
        q event t =
      concreteProjectiveAveragedCenteredCOEEventPath N K
        (concreteCentralMatrixUpdate N
          (oneColumnCenteredScalarLog m N q) ⁻¹' event) t := by
  let mu := concreteScaledCOECornerLaw
    CurrentPRL.canonicalUnitaryHaarProbabilityFamily N K
  let _ : IsProbabilityMeasure mu :=
    concreteScaledCOECornerLaw_isProbability
      CurrentPRL.canonicalUnitaryHaarProbabilityFamily hNK
  have hcentral : Measurable
      (concreteCentralMatrixUpdate N (oneColumnCenteredScalarLog m N q)) :=
    measurable_concreteCentralMatrixUpdate N _
  have hpre : MeasurableSet
      (concreteCentralMatrixUpdate N
        (oneColumnCenteredScalarLog m N q) ⁻¹' event) :=
    hcentral hevent
  rw [concreteSharedBetaOrbitalEventPath,
    concreteSharedBetaPathAction_eq_central_orbital hN]
  unfold concreteCentralMatrixKernel
  rw [Measure.deterministic_comp_eq_map]
  rw [map_measureReal_apply hcentral hevent]
  rw [concreteProjectiveAveragedCenteredCOEEventPath_eq_orbitalAction
    hN hNK _ hpre t]

end

end LogdetLean.GramHafnian.UltimateHiding.DenseLocalStep
