import LogdetLean.GramHafnian.UltimateHiding.DenseScore.H7LineIdentifications
import LogdetLean.GramHafnian.UltimateHiding.DenseScore.CenteredFlowGeometry

/-!
# Literal central-line geometry for H7

The inverse congruence flow in the identity direction is scalar multiplication
by `exp (-2t)`.  This module rewrites the arbitrary-direction determinant and
likelihood used by H7 into one explicit real log-determinant curve.  No score
identity or external declaration is used.
-/

open Function
open scoped Matrix Topology

namespace LogdetLean.GramHafnian.UltimateHiding.DenseScore

noncomputable section

open LogdetLean.GramHafnian.UltimateHiding.Dense

local instance h7CentralMatrixNormedRing {N : ℕ} :
    NormedRing (ConcreteMatrixState N) := Matrix.linftyOpNormedRing

local instance h7CentralMatrixNormedSpace {N : ℕ} :
    NormedSpace ℂ (ConcreteMatrixState N) := Matrix.linftyOpNormedSpace

local instance h7CentralMatrixNormedAlgebra {N : ℕ} :
    NormedAlgebra ℂ (ConcreteMatrixState N) := Matrix.linftyOpNormedAlgebra

/-- The transpose-congruence flow generated by the identity is scalar. -/
theorem transposeCongruenceFlow_one_eq_smul
    {N : ℕ} (t : ℝ) (C : ConcreteMatrixState N) :
    transposeCongruenceFlow (1 : ConcreteMatrixState N) t C =
      (((Real.exp (2 * t) : ℝ) : ℂ)) • C := by
  have hexp : NormedSpace.exp
      (((t : ℂ)) • (1 : ConcreteMatrixState N)) =
      (((Real.exp t : ℝ) : ℂ)) • (1 : ConcreteMatrixState N) := by
    rw [matrix_exp_smul_one]
    congr 1
    rw [← NormedSpace.ofReal_exp_ℝ_ℝ, ← Real.exp_eq_exp_ℝ]
  unfold transposeCongruenceFlow transposeCongruence
  rw [hexp]
  simp only [Matrix.transpose_smul, Matrix.transpose_one,
    Matrix.smul_mul, Matrix.one_mul, Matrix.mul_smul, Matrix.mul_one,
    smul_smul]
  congr 1
  norm_cast
  rw [← Real.exp_add]
  congr 1
  ring

/-- The literal real determinant along the inverse identity flow. -/
def h7CentralInverseDeterminant {N : ℕ} (K : ℕ)
    (A : ConcreteMatrixState N) (t : ℝ) : ℝ :=
  let C := unscaleCOECorner K A
  (Matrix.det
    (1 - (((Real.exp (-4 * t) : ℝ) : ℂ)) •
      (C.conjTranspose * C))).re

@[simp]
theorem h7CentralInverseDeterminant_zero
    {N K : ℕ} (A : ConcreteMatrixState N) :
    h7CentralInverseDeterminant K A 0 =
      concreteCOEBaseDeterminant K A := by
  simp [h7CentralInverseDeterminant, concreteCOEBaseDeterminant]

/-- The scalar central determinant is a finite polynomial in an exponential
parameter and is therefore smooth. -/
theorem h7CentralInverseDeterminant_contDiffAt_top
    {N K : ℕ} (A : ConcreteMatrixState N) :
    ContDiffAt ℝ ⊤ (h7CentralInverseDeterminant K A) 0 := by
  let C := unscaleCOECorner K A
  have hexpReal : ContDiffAt ℝ ⊤
      (fun t : ℝ => Real.exp (-4 * t)) 0 := by
    fun_prop
  have hexpComplex : ContDiffAt ℝ ⊤
      (fun t : ℝ => ((Real.exp (-4 * t) : ℝ) : ℂ)) 0 := by
    have h := Complex.ofRealCLM.contDiff.contDiffAt.comp 0 hexpReal
    simpa [Function.comp_def, Complex.ofRealCLM_apply] using h
  have hdet : ContDiffAt ℝ ⊤
      (fun t : ℝ => Matrix.det
        (1 - (((Real.exp (-4 * t) : ℝ) : ℂ)) •
          (C.conjTranspose * C))) 0 := by
    simp only [Matrix.det_apply']
    apply ContDiffAt.sum
    intro σ _
    apply ContDiffAt.mul contDiffAt_const
    apply contDiffAt_prod
    intro i _
    simp only [Matrix.sub_apply, Matrix.one_apply, Matrix.smul_apply]
    exact contDiffAt_const.sub (hexpComplex.mul contDiffAt_const)
  have hre := Complex.reCLM.contDiff.contDiffAt.comp 0 hdet
  change ContDiffAt ℝ ⊤
    (fun t : ℝ => (Matrix.det
      (1 - (((Real.exp (-4 * t) : ℝ) : ℂ)) •
        (C.conjTranspose * C))).re) 0
  simpa [Function.comp_def, Complex.reCLM_apply] using hre

/-- Logarithm of the normalized determinant on the central line. -/
def h7CentralLogDeterminantRatio {N : ℕ} (K : ℕ)
    (A : ConcreteMatrixState N) (t : ℝ) : ℝ :=
  Real.log (h7CentralInverseDeterminant K A t /
    concreteCOEBaseDeterminant K A)

/-- On support, the normalized central log determinant is locally `C³`. -/
theorem h7CentralLogDeterminantRatio_contDiffAt_three
    {N K : ℕ} (A : ConcreteMatrixState N)
    (hsupport : coeCornerSupport (unscaleCOECorner K A)) :
    ContDiffAt ℝ 3 (h7CentralLogDeterminantRatio K A) 0 := by
  have hbase : concreteCOEBaseDeterminant K A ≠ 0 :=
    ((RCLike.lt_iff_re_im.mp hsupport.det_pos).1).ne'
  have hratio : ContDiffAt ℝ 3
      (fun t : ℝ => h7CentralInverseDeterminant K A t /
        concreteCOEBaseDeterminant K A) 0 :=
    (h7CentralInverseDeterminant_contDiffAt_top A).of_le
      (by norm_num) |>.div_const _
  unfold h7CentralLogDeterminantRatio
  apply hratio.log
  rw [h7CentralInverseDeterminant_zero, div_self hbase]
  norm_num

/-- The arbitrary-direction inverse determinant restricted to the identity
line is exactly `h7CentralInverseDeterminant`. -/
theorem h16GeneralCOEInverseDeterminant_central_line
    {N K : ℕ} (A : ConcreteMatrixState N) (t : ℝ) :
    h16GeneralCOEInverseDeterminant K
        (t • (1 : ConcreteMatrixState N)) A =
      h7CentralInverseDeterminant K A t := by
  unfold h16GeneralCOEInverseDeterminant h7CentralInverseDeterminant
  dsimp only
  rw [transposeCongruenceFlow_real_smul_neg_one]
  rw [transposeCongruenceFlow_one_eq_smul]
  have hr : Real.exp (2 * -t) = Real.exp (-2 * t) := by
    congr 1
    ring
  rw [hr]
  have hsq : Real.exp (-2 * t) * Real.exp (-2 * t) =
      Real.exp (-4 * t) := by
    rw [← Real.exp_add]
    congr 1
    ring
  have hstar : star (((Real.exp (-2 * t) : ℝ) : ℂ)) =
      (((Real.exp (-2 * t) : ℝ) : ℂ)) := by
    rw [Complex.star_def, Complex.conj_ofReal]
  have hgram :
      (((((Real.exp (-2 * t) : ℝ) : ℂ)) •
          unscaleCOECorner K A).conjTranspose) *
          ((((Real.exp (-2 * t) : ℝ) : ℂ)) •
            unscaleCOECorner K A) =
        (((Real.exp (-4 * t) : ℝ) : ℂ)) •
          ((unscaleCOECorner K A).conjTranspose *
            unscaleCOECorner K A) := by
    rw [Matrix.conjTranspose_smul, hstar, Matrix.smul_mul,
      Matrix.mul_smul, smul_smul]
    congr 1
    norm_cast
    simpa using hsq
  rw [hgram]

/-- The literal central likelihood curve, with the identity-line Jacobian
and determinant ratio kept explicit. -/
def h7CentralLikelihoodCore {N : ℕ} (K : ℕ)
    (A : ConcreteMatrixState N) (t : ℝ) : ℝ := by
  classical
  exact if concreteCOEBaseDeterminant K A = 0 then 1 else
    Real.exp (-2 * (N : ℝ) * ((N : ℝ) + 1) * t) *
      Real.rpow
        (h7CentralInverseDeterminant K A t /
          concreteCOEBaseDeterminant K A)
        (coeCornerDensityExponent N K)

/-- The H7 coordinate likelihood on the central line is literally the
explicit central scalar curve. -/
theorem h16CoordinateLikelihoodCore_central_line
    {N K : ℕ} (A : ConcreteMatrixState N) :
    (fun t : ℝ => h16CoordinateLikelihoodCore K A
      (t • concreteMatrixRealCoordinates (1 : ConcreteMatrixState N))) =
    h7CentralLikelihoodCore K A := by
  funext t
  rw [h16CoordinateLikelihoodCore_matrix_line]
  unfold h16GeneralCOELikelihoodCore h7CentralLikelihoodCore
  split_ifs with hbase
  · rfl
  · rw [h16GeneralCOEInverseDeterminant_central_line]
    have htrace :
        (Matrix.trace (t • (1 : ConcreteMatrixState N))).re =
          (N : ℝ) * t := by
      change (Matrix.trace (((t : ℝ) : ℂ) •
        (1 : ConcreteMatrixState N))).re = (N : ℝ) * t
      rw [Matrix.trace_smul, Matrix.trace_one]
      simp
      ring
    rw [htrace]
    congr 1
    ring

/-- The central scalar curve is normalized on every supported state. -/
theorem h7CentralLikelihoodCore_zero_on_support
    {N K : ℕ} (A : ConcreteMatrixState N)
    (hsupport : coeCornerSupport (unscaleCOECorner K A)) :
    h7CentralLikelihoodCore K A 0 = 1 := by
  have hbase : concreteCOEBaseDeterminant K A ≠ 0 :=
    ((RCLike.lt_iff_re_im.mp hsupport.det_pos).1).ne'
  unfold h7CentralLikelihoodCore
  rw [if_neg hbase, h7CentralInverseDeterminant_zero, div_self hbase]
  simp

/-- Local `C³` regularity of the central scalar curve follows from the
already checked multivariable regularity of the literal determinant density. -/
theorem h7CentralLikelihoodCore_contDiffAt_three
    {N K : ℕ} (A : ConcreteMatrixState N)
    (hsupport : coeCornerSupport (unscaleCOECorner K A)) :
    ContDiffAt ℝ 3 (h7CentralLikelihoodCore K A) 0 := by
  rw [← h16CoordinateLikelihoodCore_central_line A]
  let i := concreteMatrixRealCoordinates (1 : ConcreteMatrixState N)
  let L : ℝ →L[ℝ] ConcreteMatrixRealCoordinates N :=
    (ContinuousLinearMap.id ℝ ℝ).smulRight i
  have hfun :
      (fun t : ℝ => h16CoordinateLikelihoodCore K A (t • i)) =
        h16CoordinateLikelihoodCore K A ∘ L := by
    funext t
    simp [L]
  rw [show (fun t : ℝ => h16CoordinateLikelihoodCore K A
    (t • concreteMatrixRealCoordinates (1 : ConcreteMatrixState N))) =
      (fun t : ℝ => h16CoordinateLikelihoodCore K A (t • i)) by rfl,
    hfun]
  have hf0 : ContDiffAt ℝ 3 (h16CoordinateLikelihoodCore K A) 0 :=
    (h16CoordinateLikelihoodCore_contDiffAt_top A hsupport).of_le (by norm_num)
  have hfL : ContDiffAt ℝ 3 (h16CoordinateLikelihoodCore K A) (L 0) := by
    simpa using hf0
  exact hfL.comp 0 L.contDiff.contDiffAt

end

end LogdetLean.GramHafnian.UltimateHiding.DenseScore
