import LogdetLean.GramHafnian.UltimateHiding.DenseScore.DistributionalConvention
import Mathlib.Analysis.Calculus.Deriv.Mul
import Mathlib.Analysis.Calculus.Deriv.Shift
import Mathlib.RingTheory.Derivation.Basic

/-!
# Algebraic density-score recurrence

Let `D` be the forward generator on test functions along `rho_t`.  With the
forward distributional convention from `DistributionalConvention`, inverse
pullback in a likelihood ratio contributes `-D`.  Hence the algebraic density
scores obey

`L_0 = 1`, `L_(r+1) = s * L_r - D(L_r)`.

This file proves the first fixed-degree consequences in an arbitrary
commutative differential algebra.  It does not assert that the COE density is
differentiable or that its analytic score has any moment bound.
-/

namespace LogdetLean.GramHafnian.UltimateHiding.DenseScore

noncomputable section

section DifferentialAlgebra

variable {R A : Type*}
variable [CommRing R] [CommRing A] [Algebra R A]

/-- Density scores generated by a first score `s` and a derivation `D`, using
the forward-pushforward sign convention. -/
def densityScoreRecurrence (D : Derivation R A A) (s : A) : ℕ → A
  | 0 => 1
  | r + 1 => s * densityScoreRecurrence D s r - D (densityScoreRecurrence D s r)

@[simp]
theorem densityScoreRecurrence_zero (D : Derivation R A A) (s : A) :
    densityScoreRecurrence D s 0 = 1 := rfl

@[simp]
theorem densityScoreRecurrence_succ
    (D : Derivation R A A) (s : A) (r : ℕ) :
    densityScoreRecurrence D s (r + 1) =
      s * densityScoreRecurrence D s r - D (densityScoreRecurrence D s r) := rfl

/-- The first density score is the likelihood score itself. -/
@[simp]
theorem densityScoreRecurrence_one (D : Derivation R A A) (s : A) :
    densityScoreRecurrence D s 1 = s := by
  simp [densityScoreRecurrence]

/-- Exact second density score for the chosen forward sign convention:
`L_2 = s^2 - D s`. -/
theorem densityScoreRecurrence_two (D : Derivation R A A) (s : A) :
    densityScoreRecurrence D s 2 = s ^ 2 - D s := by
  simp [densityScoreRecurrence, pow_two]

/-- The third algebraic score is included because it follows without any
additional analytic input. -/
theorem densityScoreRecurrence_three (D : Derivation R A A) (s : A) :
    densityScoreRecurrence D s 3 =
      s ^ 3 - 3 * (s * D s) + D (D s) := by
  rw [show (3 : ℕ) = 2 + 1 by norm_num, densityScoreRecurrence_succ,
    densityScoreRecurrence_two, Derivation.map_sub, pow_two,
    Derivation.leibniz]
  simp only [smul_eq_mul]
  ring

/-- First density Bell polynomial in the logarithmic score. -/
def firstDensityBell (ellOne : A) : A := ellOne

/-- Second density Bell polynomial in the first two logarithmic scores. -/
def secondDensityBell (ellOne ellTwo : A) : A :=
  ellOne ^ 2 + ellTwo

/-- If the second logarithmic score is `-D s`, the second Bell polynomial is
exactly the second forward density recurrence. -/
theorem secondDensityBell_eq_densityScoreRecurrence_two
    (D : Derivation R A A) (s : A) :
    secondDensityBell s (-D s) = densityScoreRecurrence D s 2 := by
  rw [densityScoreRecurrence_two]
  simp only [secondDensityBell, sub_eq_add_neg]

/-- Pointwise specialization to real-valued score functions.  This is the
literal form `L_2(x) = s(x)^2 - (D s)(x)` used in a density calculation. -/
theorem densityScoreRecurrence_two_apply
    {Omega : Type*}
    (D : Derivation ℝ (Omega → ℝ) (Omega → ℝ))
    (s : Omega → ℝ) (x : Omega) :
    densityScoreRecurrence D s 2 x = s x ^ 2 - D s x := by
  rw [densityScoreRecurrence_two]
  rfl

end DifferentialAlgebra

section LikelihoodCocycle

variable {Omega : Type*}

/-!
The next theorem is the concrete plug-in point for a future COE density proof.
It requires the literal likelihood-ratio cocycle and the two displayed
first-derivative facts; it does not package either one as an interface or
postulate it as an axiom.
-/

/-- A forward likelihood-ratio cocycle differentiates with the recurrence
`partial_t r_t = s * r_t - D r_t`.

The minus sign is forced by the inverse orbit `orbit (-h)` in `hcocycle`.
For the concrete COE density, `hinversePullback` is the analytic
differentiation theorem that remains to be proved. -/
theorem hasDerivAt_forwardLikelihoodRatio
    (orbit : ℝ → Omega → Omega)
    (ratio : ℝ → Omega → ℝ)
    (D : (Omega → ℝ) → (Omega → ℝ))
    (score : Omega → ℝ)
    (horbitZero : ∀ x, orbit 0 x = x)
    (hratioZero : ∀ x, ratio 0 x = 1)
    (hcocycle : ∀ t h x,
      ratio (t + h) x = ratio h x * ratio t (orbit (-h) x))
    (hscore : ∀ x,
      HasDerivAt (fun h ↦ ratio h x) (score x) 0)
    (hinversePullback : ∀ t x,
      HasDerivAt (fun h ↦ ratio t (orbit (-h) x))
        (-D (ratio t) x) 0)
    (t : ℝ) (x : Omega) :
    HasDerivAt (fun u ↦ ratio u x)
      (score x * ratio t x - D (ratio t) x) t := by
  have hproduct :
      HasDerivAt
        (fun h ↦ ratio h x * ratio t (orbit (-h) x))
        (score x * ratio t x - D (ratio t) x) 0 := by
    convert! (hscore x).mul (hinversePullback t x) using 1
    all_goals simp [horbitZero, hratioZero, sub_eq_add_neg]
  have hincrement :
      HasDerivAt (fun h ↦ ratio (t + h) x)
        (score x * ratio t x - D (ratio t) x) 0 :=
    hproduct.congr_of_eventuallyEq
      (Filter.Eventually.of_forall fun h ↦ hcocycle t h x)
  have hshift : HasDerivAt (fun u : ℝ ↦ u - t) 1 t :=
    (hasDerivAt_id (x := t)).sub_const t
  have hback := HasDerivAt.comp_of_eq (𝕜 := ℝ) (𝕜' := ℝ) t
    hincrement hshift (by ring)
  simpa [Function.comp_def] using hback

/-- Second density-score recurrence obtained by differentiating the
likelihood cocycle once more.  The additional hypothesis is precisely the
commutation of the concrete orbit derivation `D` with the time derivative at
zero. -/
theorem hasDerivAt_deriv_forwardLikelihoodRatio
    (orbit : ℝ → Omega → Omega)
    (ratio : ℝ → Omega → ℝ)
    (D : (Omega → ℝ) → (Omega → ℝ))
    (score : Omega → ℝ)
    (horbitZero : ∀ x, orbit 0 x = x)
    (hratioZero : ∀ x, ratio 0 x = 1)
    (hcocycle : ∀ t h x,
      ratio (t + h) x = ratio h x * ratio t (orbit (-h) x))
    (hscore : ∀ x,
      HasDerivAt (fun h ↦ ratio h x) (score x) 0)
    (hinversePullback : ∀ t x,
      HasDerivAt (fun h ↦ ratio t (orbit (-h) x))
        (-D (ratio t) x) 0)
    (hDtime : ∀ x,
      HasDerivAt (fun t ↦ D (ratio t) x) (D score x) 0)
    (x : Omega) :
    HasDerivAt (fun t ↦ deriv (fun u ↦ ratio u x) t)
      (score x ^ 2 - D score x) 0 := by
  have hrhs :
      HasDerivAt (fun t ↦ score x * ratio t x - D (ratio t) x)
        (score x ^ 2 - D score x) 0 := by
    change HasDerivAt
      ((fun t ↦ score x * ratio t x) - fun t ↦ D (ratio t) x)
      (score x ^ 2 - D score x) 0
    convert! ((hscore x).const_mul (score x)).sub (hDtime x) using 1
    simp [pow_two]
  apply hrhs.congr_of_eventuallyEq
  filter_upwards [] with t
  exact (hasDerivAt_forwardLikelihoodRatio orbit ratio D score
    horbitZero hratioZero hcocycle hscore hinversePullback t x).deriv

end LikelihoodCocycle

end

end LogdetLean.GramHafnian.UltimateHiding.DenseScore
