import A3
#check LogdetLean.GramHafnian.UltimateHiding.DenseScore.A3OriginalTarget
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.A3OriginalTarget
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.edelmanSuttonJacobiMatrix_isHermitian
