import A3.GSVAESupport
import A3.HermitianSpectrum

#print axioms A3Research.measurable_hermitian_eigenvalues
#print axioms A3Research.eigenvalues_permutation_of_unitary_diagonalization
#print axioms A3Research.measurable_canonicalHermitianSpectrum
#print axioms A3Research.canonicalHermitianSpectrum_permutation_of_diagonalization
#print axioms A3Research.canonicalHermitianSpectrum_projection
#print axioms A3Research.ae_det_leadingMinor_ne_zero
#print axioms A3Research.injective_mulVec_of_det_leadingMinor_ne_zero
#print axioms LogdetLean.GramHafnian.injective_circularGaussianCoordinate
#print axioms LogdetLean.GramHafnian.circularGaussian_nullSingletonClass
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.continuous_edelmanSuttonTotalGramSqrt
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.measurable_complexMatrix_nonsing_inv
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.measurable_edelmanSuttonJacobiMatrix
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.measurable_edelmanSuttonSquaredGSVCoordinates
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.a3_edelmanSuttonJacobiMatrix_posSemidef
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.edelmanSuttonSquaredGSVCoordinates_eq_eigenvalues
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.edelmanSuttonSquaredGSVCoordinates_mem_openUnitCube
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.ae_posDef_Gram_standardComplexGaussian
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.ae_posDef_Gram_edelmanSuttonRealGaussian
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.ae_posDef_edelmanSuttonGrams
#print axioms LogdetLean.GramHafnian.UltimateHiding.DenseScore.ae_edelmanSuttonSquaredGSVCoordinates_mem_openUnitCube
