import LogdetLean.GramHafnian.UltimateHiding.Sparse.H19HaarSuffixBlock
import LogdetLean.GramHafnian.UltimateHiding.Sparse.H19JiangRawDensity
import Mathlib.Tactic

/-!
# Exact append-one-column representation of a Haar corner

An independent Haar rotation on the final `M-L` ambient coordinates fixes
the first `L` columns.  Its first suffix column generates column `L` as the
top suffix block times a uniform Haar column.  This gives an exact joint-law
representation suitable for the Jiang-density induction.

This file uses normalized Haar invariance only.  It does not invoke Jiang's
density declaration.
-/

open MeasureTheory Matrix
open scoped BigOperators

namespace LogdetLean.GramHafnian.UltimateHiding.Sparse

noncomputable section

open LogdetLean.GramHafnian.UltimateHiding.Dense
open LogdetLean.GramHafnian.CurrentPRL

/-- Append one vector as the final column of a `Fin L`-indexed matrix. -/
def h19AppendColumn {K L : ℕ}
    (A : Matrix (Fin K) (Fin L) ℂ) (x : Fin K → ℂ) :
    Matrix (Fin K) (Fin (L + 1)) ℂ :=
  fun i ↦ Fin.snoc (A i) (x i)

@[simp]
theorem h19AppendColumn_apply_castSucc {K L : ℕ}
    (A : Matrix (Fin K) (Fin L) ℂ) (x : Fin K → ℂ)
    (i : Fin K) (j : Fin L) :
    h19AppendColumn A x i j.castSucc = A i j := by
  simp [h19AppendColumn]

@[simp]
theorem h19AppendColumn_apply_last {K L : ℕ}
    (A : Matrix (Fin K) (Fin L) ℂ) (x : Fin K → ℂ)
    (i : Fin K) :
    h19AppendColumn A x i (Fin.last L) = x i := by
  simp [h19AppendColumn]

theorem measurable_h19AppendColumn (K L : ℕ) :
    Measurable
      (fun p : Matrix (Fin K) (Fin L) ℂ × (Fin K → ℂ) ↦
        h19AppendColumn p.1 p.2) := by
  refine measurable_pi_lambda _ fun i ↦ measurable_pi_lambda _ fun j ↦ ?_
  refine Fin.lastCases ?_ (fun k ↦ ?_) j
  · simpa only [h19AppendColumn_apply_last, Function.comp_def] using
      ((measurable_pi_apply i).comp measurable_snd)
  · simpa only [h19AppendColumn_apply_castSucc, Function.comp_def] using
      ((measurable_pi_apply k).comp
        ((measurable_pi_apply i).comp measurable_fst))

/-- The first `L` columns of a Haar unitary, restricted to the top `K` rows. -/
def h19HaarTallPast {M K L : ℕ} (hKM : K ≤ M) (hLM : L ≤ M)
    (U : Matrix.unitaryGroup (Fin M) ℂ) : Matrix (Fin K) (Fin L) ℂ :=
  topLeftUnitaryBlock hKM hLM U

theorem measurable_h19HaarTallPast {M K L : ℕ}
    (hKM : K ≤ M) (hLM : L ≤ M) :
    Measurable (h19HaarTallPast hKM hLM) :=
  measurable_topLeftUnitaryBlock hKM hLM

/-- The final `M-L` columns, restricted to the top `K` rows. -/
def h19HaarTopSuffix {M K L : ℕ} (hKM : K ≤ M) (hLM : L ≤ M)
    (U : Matrix.unitaryGroup (Fin M) ℂ) :
    Matrix (Fin K) (Fin (M - L)) ℂ :=
  fun i j ↦ (U : Matrix (Fin M) (Fin M) ℂ)
    (Fin.castLE hKM i) (haarAmbientPrefixEquiv hLM (Sum.inr j))

theorem measurable_h19HaarTopSuffix {M K L : ℕ}
    (hKM : K ≤ M) (hLM : L ≤ M) :
    Measurable (h19HaarTopSuffix hKM hLM) := by
  refine measurable_pi_lambda _ fun i ↦ measurable_pi_lambda _ fun j ↦ ?_
  exact (measurable_pi_apply (haarAmbientPrefixEquiv hLM (Sum.inr j))).comp
    ((measurable_pi_apply (Fin.castLE hKM i)).comp measurable_subtype_coe)

/-- The first column of a positive-dimensional suffix Haar unitary. -/
def h19HaarSuffixFirstColumn {d : ℕ} (hd : 0 < d)
    (V : Matrix.unitaryGroup (Fin d) ℂ) : Fin d → ℂ :=
  fun j ↦ (V : Matrix (Fin d) (Fin d) ℂ) j ⟨0, hd⟩

theorem measurable_h19HaarSuffixFirstColumn {d : ℕ} (hd : 0 < d) :
    Measurable (h19HaarSuffixFirstColumn hd) := by
  unfold h19HaarSuffixFirstColumn
  refine measurable_pi_lambda _ fun j ↦ ?_
  exact (measurable_pi_apply (⟨0, hd⟩ : Fin d)).comp
    ((measurable_pi_apply j).comp measurable_subtype_coe)

/-- The new top column generated by the suffix block and an independent
suffix Haar first column. -/
def h19HaarGeneratedTopColumn {M K L : ℕ}
    (hKM : K ≤ M) (hLM : L ≤ M) (hd : 0 < M - L)
    (p : Matrix.unitaryGroup (Fin M) ℂ ×
      Matrix.unitaryGroup (Fin (M - L)) ℂ) : Fin K → ℂ :=
  h19HaarTopSuffix hKM hLM p.1 *ᵥ h19HaarSuffixFirstColumn hd p.2

theorem measurable_h19HaarGeneratedTopColumn {M K L : ℕ}
    (hKM : K ≤ M) (hLM : L ≤ M) (hd : 0 < M - L) :
    Measurable (h19HaarGeneratedTopColumn hKM hLM hd) := by
  refine measurable_pi_lambda _ fun i ↦ ?_
  unfold h19HaarGeneratedTopColumn Matrix.mulVec dotProduct
  refine Finset.measurable_sum _ fun j _ ↦ ?_
  exact ((measurable_pi_apply j).comp
      ((measurable_pi_apply i).comp
        ((measurable_h19HaarTopSuffix hKM hLM).comp measurable_fst))).mul
    ((measurable_pi_apply j).comp
      ((measurable_h19HaarSuffixFirstColumn hd).comp measurable_snd))

private theorem h19_firstSuffixIndex_eq_last
    {L M : ℕ} (hLsuccM : L + 1 ≤ M) :
    haarAmbientPrefixEquiv (show L ≤ M by omega)
        (Sum.inr (⟨0, by omega⟩ : Fin (M - L))) =
      Fin.castLE hLsuccM (Fin.last L) := by
  apply Fin.ext
  simp [haarAmbientPrefixEquiv, Fin.castLE]

/-- Pointwise form of the suffix rotation: the rotated `L+1` corner is the
old `L` corner with the generated top column appended. -/
theorem topLeft_suffixRotation_eq_h19AppendColumn
    {M K L : ℕ} (hKM : K ≤ M) (hLsuccM : L + 1 ≤ M)
    (U : Matrix.unitaryGroup (Fin M) ℂ)
    (V : Matrix.unitaryGroup (Fin (M - L)) ℂ) :
    topLeftUnitaryBlock hKM hLsuccM
        (U * h19HaarAmbientSuffixUnitary (show L ≤ M by omega) V) =
      h19AppendColumn
        (h19HaarTallPast hKM (show L ≤ M by omega) U)
        (h19HaarGeneratedTopColumn hKM (show L ≤ M by omega)
          (by omega : 0 < M - L) (U, V)) := by
  let hLM : L ≤ M := by omega
  let hd : 0 < M - L := by omega
  let e := haarAmbientPrefixEquiv hLM
  ext i j
  refine Fin.lastCases ?_ (fun q ↦ ?_) j
  · change
      ((U * h19HaarAmbientSuffixUnitary hLM V :
          Matrix.unitaryGroup (Fin M) ℂ) : Matrix (Fin M) (Fin M) ℂ)
          (Fin.castLE hKM i) (Fin.castLE hLsuccM (Fin.last L)) = _
    rw [h19AppendColumn_apply_last]
    unfold h19HaarGeneratedTopColumn h19HaarTopSuffix
      h19HaarSuffixFirstColumn Matrix.mulVec dotProduct
    rw [← h19_firstSuffixIndex_eq_last hLsuccM]
    simp only [Submonoid.coe_mul, Matrix.mul_apply]
    rw [← Fintype.sum_equiv e
      (fun a : Fin L ⊕ Fin (M - L) ↦
        (U : Matrix (Fin M) (Fin M) ℂ) (Fin.castLE hKM i) (e a) *
          (h19HaarAmbientSuffixUnitary hLM V :
            Matrix (Fin M) (Fin M) ℂ) (e a) (e (Sum.inr ⟨0, hd⟩)))
      (fun a : Fin M ↦
        (U : Matrix (Fin M) (Fin M) ℂ) (Fin.castLE hKM i) a *
          (h19HaarAmbientSuffixUnitary hLM V :
            Matrix (Fin M) (Fin M) ℂ) a (e (Sum.inr ⟨0, hd⟩)))
      (fun _ ↦ rfl)]
    rw [Fintype.sum_sum_type]
    simp [e]
  · change
      ((U * h19HaarAmbientSuffixUnitary hLM V :
          Matrix.unitaryGroup (Fin M) ℂ) : Matrix (Fin M) (Fin M) ℂ)
          (Fin.castLE hKM i) (Fin.castLE hLsuccM q.castSucc) = _
    have hindex : Fin.castLE hLsuccM q.castSucc = Fin.castLE hLM q := by
      apply Fin.ext
      rfl
    rw [hindex,
      mul_h19HaarAmbientSuffixUnitary_apply_leading hLM U V]
    simp only [h19AppendColumn_apply_castSucc, h19HaarTallPast,
      topLeftUnitaryBlock]

/-- Exact append-one-column law for the unscaled tall Haar corner.  The
source keeps the ambient Haar unitary and the independent suffix Haar unitary
visible, which is the form needed for the subsequent conditional-density
identification. -/
theorem jiangUnscaledTallHaarCornerLaw_succ_eq_suffixHaar_append
    {M K L : ℕ} (hKM : K ≤ M) (hLsuccM : L + 1 ≤ M) :
    jiangUnscaledTallHaarCornerLaw M K (L + 1) =
      Measure.map
        (fun p : Matrix.unitaryGroup (Fin M) ℂ ×
            Matrix.unitaryGroup (Fin (M - L)) ℂ ↦
          h19AppendColumn
            (h19HaarTallPast hKM
              (show L ≤ M by omega) p.1)
            (h19HaarGeneratedTopColumn hKM
              (show L ≤ M by omega) (by omega : 0 < M - L) p))
        ((unitaryHaarProbabilityMeasure M).prod
          (unitaryHaarProbabilityMeasure (M - L))) := by
  have hLM : L ≤ M := by omega
  let rotate := fun p : Matrix.unitaryGroup (Fin M) ℂ ×
      Matrix.unitaryGroup (Fin (M - L)) ℂ ↦
        p.1 * h19HaarAmbientSuffixUnitary hLM p.2
  let corner := topLeftUnitaryBlock hKM hLsuccM
  have hrotate : Measurable rotate :=
    measurable_mul_h19HaarAmbientSuffixUnitary_uncurry hLM
  have hcorner : Measurable corner :=
    measurable_topLeftUnitaryBlock hKM hLsuccM
  rw [jiangUnscaledTallHaarCornerLaw, dif_pos ⟨hKM, hLsuccM⟩]
  calc
    Measure.map corner (unitaryHaarProbabilityMeasure M) =
        Measure.map corner (Measure.map rotate
          ((unitaryHaarProbabilityMeasure M).prod
            (unitaryHaarProbabilityMeasure (M - L)))) := by
      rw [map_mul_h19HaarAmbientSuffixUnitary_prod_haar hLM]
    _ = Measure.map (corner ∘ rotate)
          ((unitaryHaarProbabilityMeasure M).prod
            (unitaryHaarProbabilityMeasure (M - L))) := by
      rw [Measure.map_map hcorner hrotate]
    _ = _ := by
      apply Measure.map_congr
      filter_upwards with p
      exact topLeft_suffixRotation_eq_h19AppendColumn hKM hLsuccM p.1 p.2

end

end LogdetLean.GramHafnian.UltimateHiding.Sparse
