import LogdetLean.GramHafnian.UltimateHiding.DenseScore.Conditional.H16_Proof

/-!
# U07 compact-`L1` consumer inputs generated by H16 transport

This module packages the three downstream scientific contracts that follow
immediately from a universally quantified event-free H16 transport family:

* the exact original fixed-direction H16 identity;
* genuine fixed-direction `C^4` regularity; and
* almost-sure membership in the scaled symmetric COE support.

The proposition bodies are quantifier-for-quantifier the contracts consumed
by U07's `H17_CompactL1_Proof` and `H18_CompactL1_Proof`.  The remaining
fourth U07 input is the compact-time, projective, zero-extended `L1` envelope;
it does not follow from a merely direction-by-direction transport family and
must be supplied by `COECenteredOrderFourZeroExtensionFacts`.
-/

open MeasureTheory
open scoped ContDiff

namespace LogdetLean.GramHafnian.UltimateHiding.DenseScore

noncomputable section

open LogdetLean.GramHafnian.UltimateHiding.Dense
open LogdetLean.GramHafnian.LocalAnticoncentration

/-- Universally quantified event-free fixed-direction transport output. -/
abbrev H16FixedDirectionW41TransportFamily
    (hH5 : H16ExactH5Family) : Type :=
  ∀ {N K : ℕ} (hN : 1 ≤ N) (hboundary : 2 * N + 8 ≤ K)
    (v : ComplexUnitSphere N),
      H16FixedDirectionW41Transport hH5 hN hboundary v

/-- Exact body of U07's `CoeCornerCenteredFixedDirectionH16Contract`. -/
abbrev H16DownstreamFixedDirectionH16Contract : Prop :=
  ∀ {N K r : ℕ}, (1 ≤ N) → (2 * N + 8 ≤ K) → (r ≤ 4) →
    (v : ComplexUnitSphere N) →
    (event : Set (ConcreteMatrixState N)) → MeasurableSet event →
    iteratedDeriv r (concreteCenteredRankOneCOEEventPath K v event) 0 =
      ∫ A, event.indicator
        (concreteCenteredDensityScore r N K v) A
        ∂(concreteScaledCOECornerLaw
          canonicalUnitaryHaarProbabilityFamily N K)

/-- Exact body of U07's `CoeCornerCenteredFixedDirectionC4Contract`. -/
abbrev H16DownstreamFixedDirectionC4Contract : Prop :=
  ∀ {N K : ℕ}, (1 ≤ N) → (2 * N + 8 ≤ K) →
    (v : ComplexUnitSphere N) →
    (event : Set (ConcreteMatrixState N)) → MeasurableSet event →
    ContDiff ℝ 4 (concreteCenteredRankOneCOEEventPath K v event)

/-- Exact body of U07's `CoeCornerCenteredScaledCOESupportContract`. -/
abbrev H16DownstreamScaledCOESupportContract : Prop :=
  ∀ {N K : ℕ}, (1 ≤ N) → (2 * N + 8 ≤ K) →
    ∀ᵐ A ∂(concreteScaledCOECornerLaw
      canonicalUnitaryHaarProbabilityFamily N K),
      (unscaleCOECorner K A).IsSymm ∧
        coeCornerSupport (unscaleCOECorner K A)

/-- Exact H5 discharges U07's order-independent scaled-law support input. -/
theorem h16DownstreamScaledCOESupport_of_exactH5
    (hH5 : H16ExactH5Family) :
    H16DownstreamScaledCOESupportContract := by
  intro N K hN hboundary
  exact h16_scaledCOECorner_ae_support_of_exactH5
    hH5 hN (by omega)

/-- A single event-free transport family discharges U07's exact H16 input. -/
theorem h16DownstreamFixedDirectionH16_of_transportFamily
    (hH5 : H16ExactH5Family)
    (T : H16FixedDirectionW41TransportFamily hH5) :
    H16DownstreamFixedDirectionH16Contract := by
  intro N K r hN hboundary hr v event hevent
  exact coeCorner_centeredFixedDirection_eventPath_derivative_H16_conditional
    hH5 hN hboundary hr v (T hN hboundary v) event hevent

/-- The same event-free transport family supplies genuine `C^4` for every
fixed direction and every measurable event. -/
theorem h16DownstreamFixedDirectionC4_of_transportFamily
    (hH5 : H16ExactH5Family)
    (T : H16FixedDirectionW41TransportFamily hH5) :
    H16DownstreamFixedDirectionC4Contract := by
  intro N K hN hboundary v event hevent
  let Tv := T hN hboundary v
  have hpath : concreteCenteredRankOneCOEEventPath K v event =
      fun t ↦ h16SetIntegralL1CLM Tv.ambient event (Tv.densityPath t) := by
    funext t
    rw [Tv.eventPath_eq_setIntegral event hevent t]
    exact (h16SetIntegralL1CLM_apply
      Tv.ambient event (Tv.densityPath t)).symm
  rw [hpath]
  exact (h16SetIntegralL1CLM Tv.ambient event).contDiff.fun_comp
    Tv.densityPath_contDiff_four

end

end LogdetLean.GramHafnian.UltimateHiding.DenseScore
