import LogdetLean.GramHafnian.UltimateHiding.Dense.H1_RowStiefelDefinitions
import Mathlib.Tactic

/-!
# Deterministic row-Gram algebra for H1

This file contains the finite matrix identities behind the row-Stiefel
deletion step.  It contains no probability or random-matrix input.
-/

open scoped ComplexConjugate Matrix

namespace LogdetLean.GramHafnian.UltimateHiding.Dense

noncomputable section

open LogdetLean.GramHafnian.CurrentPRL
open LogdetLean.GramHafnian.UltimateHiding.Sparse

/-- Hermitian row Gram matrix of a rectangular complex matrix. -/
def hermitianRowGram {r c : Type*} [Fintype c]
    (X : Matrix r c ℂ) : Matrix r r ℂ :=
  X * X.conjTranspose

/-- The entries of the last column in the first `N` rows. -/
def h1TopLastColumn {N m : ℕ} (hNsucc : N ≤ m + 1)
    (U : Matrix.unitaryGroup (Fin (m + 1)) ℂ) : Fin N → ℂ :=
  fun i ↦ (U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ)
    (Fin.castLE hNsucc i) (Fin.last m)

/-- Rank-one Hermitian matrix generated by an arbitrary column vector. -/
def h1ColumnRankOne {N : ℕ} (c : Fin N → ℂ) :
    Matrix (Fin N) (Fin N) ℂ :=
  fun i j ↦ c i * star (c j)

theorem hermitianRowGram_sqrtScaledFullTopRows
    {N m : ℕ} (hNm : N ≤ m)
    (U : Matrix.unitaryGroup (Fin m) ℂ) :
    hermitianRowGram (sqrtScaledFullTopRows hNm U) =
      ((m : ℂ) • (1 : Matrix (Fin N) (Fin N) ℂ)) := by
  ext i j
  have hU := Unitary.coe_mul_star_self U
  have hij := congrArg
    (fun A : Matrix (Fin m) (Fin m) ℂ ↦
      A (Fin.castLE hNm i) (Fin.castLE hNm j)) hU
  have hsum :
      (∑ k : Fin m,
        (U : Matrix (Fin m) (Fin m) ℂ) (Fin.castLE hNm i) k *
          star ((U : Matrix (Fin m) (Fin m) ℂ)
            (Fin.castLE hNm j) k)) =
        (1 : Matrix (Fin m) (Fin m) ℂ)
          (Fin.castLE hNm i) (Fin.castLE hNm j) := by
    simpa [Matrix.mul_apply, Matrix.star_eq_conjTranspose,
      Matrix.conjTranspose_apply] using hij
  let s : ℂ := (Real.sqrt (m : ℝ) : ℝ)
  have hs : s * star s = (m : ℂ) := by
    have hsR : Real.sqrt (m : ℝ) * Real.sqrt (m : ℝ) = (m : ℝ) :=
      Real.mul_self_sqrt (Nat.cast_nonneg m)
    have hstar : star ((Real.sqrt (m : ℝ) : ℝ) : ℂ) =
        ((Real.sqrt (m : ℝ) : ℝ) : ℂ) := by simp
    dsimp only [s]
    rw [hstar]
    change ((Real.sqrt (m : ℝ) : ℝ) : ℂ) *
      ((Real.sqrt (m : ℝ) : ℝ) : ℂ) = (m : ℂ)
    exact_mod_cast hsR
  change (∑ k : Fin m,
      (s * (U : Matrix (Fin m) (Fin m) ℂ) (Fin.castLE hNm i) k) *
        star (s * (U : Matrix (Fin m) (Fin m) ℂ)
          (Fin.castLE hNm j) k)) = _
  calc
    (∑ k : Fin m,
      (s * (U : Matrix (Fin m) (Fin m) ℂ) (Fin.castLE hNm i) k) *
        star (s * (U : Matrix (Fin m) (Fin m) ℂ)
          (Fin.castLE hNm j) k)) =
        (s * star s) * ∑ k : Fin m,
          (U : Matrix (Fin m) (Fin m) ℂ) (Fin.castLE hNm i) k *
            star ((U : Matrix (Fin m) (Fin m) ℂ)
              (Fin.castLE hNm j) k) := by
          rw [Finset.mul_sum]
          apply Finset.sum_congr rfl
          intro k _
          rw [star_mul]
          ring
    _ = (m : ℂ) *
        (1 : Matrix (Fin m) (Fin m) ℂ)
          (Fin.castLE hNm i) (Fin.castLE hNm j) := by rw [hs, hsum]
    _ = ((m : ℂ) • (1 : Matrix (Fin N) (Fin N) ℂ)) i j := by
      simp only [Matrix.smul_apply, smul_eq_mul, Matrix.one_apply]
      by_cases hij' : i = j
      · subst j
        simp
      · have hcast : Fin.castLE hNm i ≠ Fin.castLE hNm j := by
          exact fun h ↦ hij' (Fin.castLE_injective hNm h)
        simp [hij', hcast]

theorem hermitianRowGram_sqrtScaledDeleteLastTopRows
    {N m : ℕ} (hNsucc : N ≤ m + 1)
    (U : Matrix.unitaryGroup (Fin (m + 1)) ℂ) :
    hermitianRowGram (sqrtScaledDeleteLastTopRows hNsucc U) =
      ((m + 1 : ℂ) •
        ((1 : Matrix (Fin N) (Fin N) ℂ) -
          h1ColumnRankOne (h1TopLastColumn hNsucc U))) := by
  ext i j
  let ri : Fin (m + 1) := Fin.castLE hNsucc i
  let rj : Fin (m + 1) := Fin.castLE hNsucc j
  have hU := Unitary.coe_mul_star_self U
  have hij := congrArg
    (fun A : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ ↦ A ri rj) hU
  have hsplit :
      (∑ k : Fin m,
          (U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ) ri k.castSucc *
            star ((U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ)
              rj k.castSucc)) +
          (U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ) ri (Fin.last m) *
            star ((U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ)
              rj (Fin.last m)) =
        (1 : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ) ri rj := by
    simpa [Matrix.mul_apply, Matrix.star_eq_conjTranspose,
      Matrix.conjTranspose_apply, Fin.sum_univ_castSucc] using hij
  let s : ℂ := (Real.sqrt ((m + 1 : ℕ) : ℝ) : ℝ)
  have hsqrt : s * star s = (m + 1 : ℂ) := by
    have hsR : Real.sqrt ((m + 1 : ℕ) : ℝ) *
        Real.sqrt ((m + 1 : ℕ) : ℝ) = ((m + 1 : ℕ) : ℝ) :=
      Real.mul_self_sqrt (Nat.cast_nonneg (m + 1))
    have hstar : star ((Real.sqrt ((m + 1 : ℕ) : ℝ) : ℝ) : ℂ) =
        ((Real.sqrt ((m + 1 : ℕ) : ℝ) : ℂ)) := by simp
    dsimp only [s]
    rw [hstar]
    change ((Real.sqrt ((m + 1 : ℕ) : ℝ) : ℝ) : ℂ) *
      ((Real.sqrt ((m + 1 : ℕ) : ℝ) : ℂ)) = (m + 1 : ℂ)
    exact_mod_cast hsR
  change (∑ k : Fin m,
      (s * (U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ) ri k.castSucc) *
        star (s * (U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ)
          rj k.castSucc)) = _
  calc
    (∑ k : Fin m,
      (s * (U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ) ri k.castSucc) *
        star (s * (U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ)
          rj k.castSucc)) =
      (s * star s) * ∑ k : Fin m,
        (U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ) ri k.castSucc *
          star ((U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ)
            rj k.castSucc) := by
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro k _
      rw [star_mul]
      ring
    _ = (m + 1 : ℂ) *
      (∑ k : Fin m,
        (U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ) ri k.castSucc *
          star ((U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ)
            rj k.castSucc)) := by rw [hsqrt]
    _ = (m + 1 : ℂ) *
      ((1 : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ) ri rj -
        (U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ) ri (Fin.last m) *
          star ((U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ)
            rj (Fin.last m))) := by
      rw [show (∑ k : Fin m,
        (U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ) ri k.castSucc *
          star ((U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ)
            rj k.castSucc)) =
      (1 : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ) ri rj -
        (U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ) ri (Fin.last m) *
          star ((U : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ)
            rj (Fin.last m)) by exact eq_sub_of_add_eq hsplit]
    _ = ((m + 1 : ℂ) •
        ((1 : Matrix (Fin N) (Fin N) ℂ) -
          h1ColumnRankOne (h1TopLastColumn hNsucc U))) i j := by
      have hone :
          (1 : Matrix (Fin (m + 1)) (Fin (m + 1)) ℂ) ri rj =
            (1 : Matrix (Fin N) (Fin N) ℂ) i j := by
        simp [Matrix.one_apply, ri, rj]
      rw [hone]
      rfl

theorem complexRankOneProjection_conjTranspose {N : ℕ}
    (v : ComplexUnitSphere N) :
    (complexRankOneProjection v).conjTranspose =
      complexRankOneProjection v := by
  ext i j
  simp [complexRankOneProjection, Matrix.conjTranspose_apply, mul_comm]

theorem complexRankOneProjection_mul_self_h1 {N : ℕ}
    (v : ComplexUnitSphere N) :
    complexRankOneProjection v * complexRankOneProjection v =
      complexRankOneProjection v := by
  ext i j
  simp only [Matrix.mul_apply, complexRankOneProjection]
  calc
    ∑ k, (v.1 i * star (v.1 k)) * (v.1 k * star (v.1 j)) =
        (v.1 i * star (v.1 j)) * ∑ k, star (v.1 k) * v.1 k := by
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro k _
      ring
    _ = v.1 i * star (v.1 j) := by
      have hvnorm : ‖v.1‖ = 1 := mem_sphere_zero_iff_norm.mp v.2
      have hsumNorm : ∑ k, ‖v.1 k‖ ^ 2 = 1 := by
        have hsq := PiLp.norm_sq_eq_of_L2 (fun _ : Fin N ↦ ℂ) v.1
        rw [hvnorm] at hsq
        norm_num at hsq ⊢
        exact hsq.symm
      have hsum : ∑ k, star (v.1 k) * v.1 k = (1 : ℂ) := by
        calc
          ∑ k, star (v.1 k) * v.1 k =
              ∑ k, ((‖v.1 k‖ ^ 2 : ℝ) : ℂ) := by
                apply Finset.sum_congr rfl
                intro k _
                rw [show star (v.1 k) * v.1 k =
                    (Complex.normSq (v.1 k) : ℂ) by
                  simpa using
                    (Complex.normSq_eq_conj_mul_self (z := v.1 k)).symm,
                  Complex.normSq_eq_norm_sq]
          _ = ((∑ k, ‖v.1 k‖ ^ 2 : ℝ) : ℂ) := by
                rw [Complex.ofReal_sum]
          _ = 1 := by rw [hsumNorm]; norm_num
      rw [hsum, mul_one]

/-- The row Gram of the independent lower-dimensional Haar update is the
same rank-one defect dictated by the beta/sphere parameter. -/
theorem hermitianRowGram_scaledRowStiefelDeletionUpdate
    {N m : ℕ} (hN : 1 ≤ N) (hNm : N ≤ m)
    (U : Matrix.unitaryGroup (Fin m) ℂ)
    (q : ℝ) (hq : 0 ≤ q) (v : ComplexUnitSphere N) :
    hermitianRowGram
        (scaledRowStiefelDeletionUpdate hNm (U, (q, v))) =
      ((m + 1 : ℂ) •
        ((1 : Matrix (Fin N) (Fin N) ℂ) -
          (((1 - q : ℝ) : ℂ)) • complexRankOneProjection v)) := by
  have hm : 1 ≤ m := hN.trans hNm
  have hmr : (0 : ℝ) < m := by exact_mod_cast hm
  have hsqrtq : Real.sqrt q ^ 2 = q := Real.sq_sqrt hq
  have hratio : Real.sqrt (((m + 1 : ℕ) : ℝ) / (m : ℝ)) ^ 2 =
      ((m + 1 : ℕ) : ℝ) / (m : ℝ) := by
    exact Real.sq_sqrt (by positivity)
  have hPstar : (complexRankOneProjection v).conjTranspose =
      complexRankOneProjection v :=
    complexRankOneProjection_conjTranspose v
  have hPmul : complexRankOneProjection v * complexRankOneProjection v =
      complexRankOneProjection v := complexRankOneProjection_mul_self_h1 v
  have hbR : (Real.sqrt q - 1) + (Real.sqrt q - 1) +
      (Real.sqrt q - 1) * (Real.sqrt q - 1) = q - 1 := by
    nlinarith [hsqrtq]
  have hbC : (((Real.sqrt q - 1 : ℝ) : ℂ)) +
        (((Real.sqrt q - 1 : ℝ) : ℂ)) +
        (((Real.sqrt q - 1 : ℝ) : ℂ)) *
          (((Real.sqrt q - 1 : ℝ) : ℂ)) =
      (((q - 1 : ℝ) : ℂ)) := by
    exact_mod_cast hbR
  have hX := hermitianRowGram_sqrtScaledFullTopRows hNm U
  change sqrtScaledFullTopRows hNm U *
      (sqrtScaledFullTopRows hNm U).conjTranspose =
        ((m : ℂ) • (1 : Matrix (Fin N) (Fin N) ℂ)) at hX
  change
    concreteOneColumnFactor m N q v * sqrtScaledFullTopRows hNm U *
        (concreteOneColumnFactor m N q v *
          sqrtScaledFullTopRows hNm U).conjTranspose = _
  rw [Matrix.conjTranspose_mul]
  calc
    concreteOneColumnFactor m N q v * sqrtScaledFullTopRows hNm U *
        ((sqrtScaledFullTopRows hNm U).conjTranspose *
          (concreteOneColumnFactor m N q v).conjTranspose) =
      concreteOneColumnFactor m N q v *
          (sqrtScaledFullTopRows hNm U *
            (sqrtScaledFullTopRows hNm U).conjTranspose) *
          (concreteOneColumnFactor m N q v).conjTranspose := by
            simp only [Matrix.mul_assoc]
    _ = concreteOneColumnFactor m N q v *
          ((m : ℂ) • (1 : Matrix (Fin N) (Fin N) ℂ)) *
          (concreteOneColumnFactor m N q v).conjTranspose := by rw [hX]
    _ = _ := by
      simp only [Matrix.mul_smul, Matrix.smul_mul, Matrix.mul_one]
      unfold concreteOneColumnFactor
      simp only [Matrix.conjTranspose_smul, Matrix.conjTranspose_add,
        Matrix.conjTranspose_one, hPstar, star_trivial, Complex.ofReal_re]
      simp only [Matrix.smul_mul, Matrix.mul_smul, smul_smul]
      rw [show (m : ℂ) *
          (star (Real.sqrt (((m + 1 : ℕ) : ℝ) / (m : ℝ)) : ℂ) *
            (Real.sqrt (((m + 1 : ℕ) : ℝ) / (m : ℝ)) : ℂ)) =
          (m + 1 : ℂ) by
        have hstar : star
            ((Real.sqrt (((m + 1 : ℕ) : ℝ) / (m : ℝ)) : ℂ)) =
            ((Real.sqrt (((m + 1 : ℕ) : ℝ) / (m : ℝ)) : ℂ)) := by simp
        rw [hstar]
        norm_cast
        rw [← pow_two, hratio]
        field_simp]
      rw [show star (((Real.sqrt q - 1 : ℝ) : ℂ)) =
          (((Real.sqrt q - 1 : ℝ) : ℂ)) by simp]
      have hinner :
          ((1 : Matrix (Fin N) (Fin N) ℂ) +
              (((Real.sqrt q - 1 : ℝ) : ℂ)) • complexRankOneProjection v) *
            ((1 : Matrix (Fin N) (Fin N) ℂ) +
              (((Real.sqrt q - 1 : ℝ) : ℂ)) • complexRankOneProjection v) =
          (1 : Matrix (Fin N) (Fin N) ℂ) -
            (((1 - q : ℝ) : ℂ)) • complexRankOneProjection v := by
        simp only [Matrix.add_mul, Matrix.mul_add, Matrix.one_mul,
          Matrix.mul_one, Matrix.smul_mul, Matrix.mul_smul, smul_smul, hPmul]
        ext i j
        simp only [Matrix.add_apply, Matrix.sub_apply, Matrix.smul_apply]
        push_cast at hbC ⊢
        linear_combination (complexRankOneProjection v i j) * hbC
      rw [hinner]

end

end LogdetLean.GramHafnian.UltimateHiding.Dense
