import LogdetLean.GramHafnian.ShiftedAnticoncentration.FourierCompression.CofactorPhaseSymmetry
import LogdetLean.GramHafnian.ShiftedAnticoncentration.FourierCompression.CoordinateIteration
import LogdetLean.GramHafnian.ShiftedAnticoncentration.GaussianDisk
import Mathlib.Analysis.Complex.Isometry
import Mathlib.FieldTheory.IsAlgClosed.Basic

/-!
# The finite Gram-cofactor characteristic function

This file packages the deterministic cofactor algebra as the literal Fourier
functional consumed by `CoordinateIteration`.  It also proves the two global
symmetries of that functional from the iid circular Gaussian law: permutation
exchangeability and common-phase invariance (in positive cofactor degree).
-/

open MeasureTheory ProbabilityTheory
open scoped BigOperators

namespace LogdetLean.GramHafnian

noncomputable section

/-- Real Fourier phase paired with the finite Gram-cofactor vector. -/
def finiteGramCofactorPhase
    {ι : Type*} [Fintype ι] [LinearOrder ι] {k : ℕ}
    (A : ι → (Fin k → ℂ)) (w : ι → ℂ) : ℝ :=
  (∑ j : ι, w j * finiteGramCofactorVector A j).re

/-- The unit-modulus Fourier character of the cofactor phase. -/
def finiteGramCofactorPhaseCharacter
    {ι : Type*} [Fintype ι] [LinearOrder ι] {k : ℕ}
    (w : ι → ℂ) (A : ι → (Fin k → ℂ)) : ℂ :=
  Complex.exp ((finiteGramCofactorPhase A w : ℂ) * Complex.I)

/-- Characteristic functional of the Gram-cofactor vector generated by iid
circular Gaussian columns. -/
def finiteGramCofactorCharacteristic
    (ι : Type*) [Fintype ι] [LinearOrder ι] (k : ℕ) :
    (ι → ℂ) → ℂ :=
  fun w ↦ ∫ A : ι → (Fin k → ℂ),
    finiteGramCofactorPhaseCharacter w A
      ∂(Measure.pi fun _ : ι ↦ circularGaussianVector k)

theorem continuous_finiteGramCofactorVector_apply
    {ι : Type*} [Fintype ι] [LinearOrder ι] {k : ℕ} (j : ι) :
    Continuous (fun A : ι → (Fin k → ℂ) ↦
      finiteGramCofactorVector A j) := by
  unfold finiteGramCofactorVector columnTransposeGram typeHafnian
    typeMatchingMonomial
  fun_prop

theorem measurable_finiteGramCofactorVector_apply
    {ι : Type*} [Fintype ι] [LinearOrder ι] {k : ℕ} (j : ι) :
    Measurable (fun A : ι → (Fin k → ℂ) ↦
      finiteGramCofactorVector A j) :=
  (continuous_finiteGramCofactorVector_apply j).measurable

theorem continuous_finiteGramCofactorPhase
    {ι : Type*} [Fintype ι] [LinearOrder ι] {k : ℕ}
    (w : ι → ℂ) :
    Continuous (fun A : ι → (Fin k → ℂ) ↦
      finiteGramCofactorPhase A w) := by
  unfold finiteGramCofactorPhase
  apply Complex.continuous_re.comp
  apply continuous_finsetSum
  intro j _hj
  exact continuous_const.mul
    (continuous_finiteGramCofactorVector_apply j)

theorem measurable_finiteGramCofactorPhaseCharacter
    {ι : Type*} [Fintype ι] [LinearOrder ι] {k : ℕ}
    (w : ι → ℂ) :
    Measurable (finiteGramCofactorPhaseCharacter (k := k) w) := by
  unfold finiteGramCofactorPhaseCharacter
  exact Complex.continuous_exp.measurable.comp
    ((Complex.continuous_ofReal.comp
      (continuous_finiteGramCofactorPhase w)).mul continuous_const).measurable

theorem finiteGramCofactorPhase_reindex_equiv
    {α β : Type*} [Fintype α] [LinearOrder α]
    [Fintype β] [LinearOrder β] {k : ℕ}
    (e : α ≃ β) (A : β → (Fin k → ℂ)) (w : β → ℂ) :
    finiteGramCofactorPhase (fun i ↦ A (e i)) (fun i ↦ w (e i)) =
      finiteGramCofactorPhase A w := by
  unfold finiteGramCofactorPhase
  congr 1
  simp_rw [finiteGramCofactorVector_reindex_equiv]
  apply Fintype.sum_equiv e
  intro i
  rfl

/-- Reindex a finite family by precomposition. -/
def reindexFiniteColumnFamily
    {α β : Type*} {k : ℕ} (e : α ≃ β)
    (A : β → (Fin k → ℂ)) : α → (Fin k → ℂ) :=
  fun i ↦ A (e i)

theorem measurePreserving_reindexFiniteColumnFamily_pi
    {ι : Type*} [Fintype ι] {k : ℕ} (σ : Equiv.Perm ι) :
    MeasurePreserving (reindexFiniteColumnFamily (k := k) σ)
      (Measure.pi fun _ : ι ↦ circularGaussianVector k)
      (Measure.pi fun _ : ι ↦ circularGaussianVector k) := by
  have hfun : reindexFiniteColumnFamily (k := k) σ =
      (MeasurableEquiv.piCongrLeft
        (fun _ : ι ↦ Fin k → ℂ) σ.symm :
          (ι → (Fin k → ℂ)) → (ι → (Fin k → ℂ))) := by
    funext A
    ext i p
    have h := MeasurableEquiv.piCongrLeft_apply_apply
      (β := fun _ : ι ↦ Fin k → ℂ) σ.symm A (σ i)
    simpa [reindexFiniteColumnFamily] using
      congrArg (fun f ↦ f p) h.symm
  rw [hfun]
  simpa using
    (measurePreserving_piCongrLeft
      (α := fun _ : ι ↦ Fin k → ℂ)
      (fun _ : ι ↦ circularGaussianVector k) σ.symm)

theorem finiteGramCofactorCharacteristic_reindex_perm
    {ι : Type*} [Fintype ι] [LinearOrder ι] {k : ℕ}
    (σ : Equiv.Perm ι) (w : ι → ℂ) :
    finiteGramCofactorCharacteristic ι k (fun i ↦ w (σ i)) =
      finiteGramCofactorCharacteristic ι k w := by
  let e : (ι → (Fin k → ℂ)) ≃ᵐ (ι → (Fin k → ℂ)) :=
    MeasurableEquiv.piCongrLeft (fun _ : ι ↦ Fin k → ℂ) σ.symm
  have he : MeasurePreserving e
      (Measure.pi fun _ : ι ↦ circularGaussianVector k)
      (Measure.pi fun _ : ι ↦ circularGaussianVector k) := by
    have h := measurePreserving_reindexFiniteColumnFamily_pi
      (k := k) σ
    rw [show (e : (ι → (Fin k → ℂ)) → (ι → (Fin k → ℂ))) =
      reindexFiniteColumnFamily (k := k) σ by
        funext A
        ext i p
        have h := MeasurableEquiv.piCongrLeft_apply_apply
          (β := fun _ : ι ↦ Fin k → ℂ) σ.symm A (σ i)
        simpa [e, reindexFiniteColumnFamily] using
          congrArg (fun f ↦ f p) h]
    exact h
  unfold finiteGramCofactorCharacteristic
  rw [← he.integral_comp']
  apply integral_congr_ae
  filter_upwards [] with A
  unfold finiteGramCofactorPhaseCharacter
  congr 2
  have he_apply : e A = reindexFiniteColumnFamily (k := k) σ A := by
    ext i p
    have h := MeasurableEquiv.piCongrLeft_apply_apply
      (β := fun _ : ι ↦ Fin k → ℂ) σ.symm A (σ i)
    simpa [e, reindexFiniteColumnFamily] using
      congrArg (fun f ↦ f p) h
  rw [he_apply]
  exact congrArg ((↑) : ℝ → ℂ)
    (finiteGramCofactorPhase_reindex_equiv σ A w)

/-- Multiplication by a unit complex number preserves the standard circular
complex Gaussian law. -/
theorem measurePreserving_circularGaussian_mul
    (c : ℂ) (hc : ‖c‖ = 1) :
    MeasurePreserving (fun z : ℂ ↦ c * z)
      circularGaussian circularGaussian := by
  let u : Circle := ⟨c, by
    change c ∈ Metric.sphere (0 : ℂ) 1
    simpa [Metric.mem_sphere] using hc⟩
  let R : ℂ ≃ₗᵢ[ℝ] ℂ := rotation u
  have hR : (stdGaussian ℂ).map R = stdGaussian ℂ :=
    stdGaussian_map R
  refine ⟨by fun_prop, ?_⟩
  rw [circularGaussian_eq_map_smul_stdGaussian]
  let s : ℝ := (Real.sqrt 2)⁻¹
  calc
    ((stdGaussian ℂ).map (fun z : ℂ ↦ s • z)).map
        (fun z : ℂ ↦ c * z) =
        (stdGaussian ℂ).map
          ((fun z : ℂ ↦ c * z) ∘ (fun z : ℂ ↦ s • z)) := by
            rw [Measure.map_map (by fun_prop) (by fun_prop)]
    _ = (stdGaussian ℂ).map
          ((fun z : ℂ ↦ s • z) ∘ R) := by
            congr 1
            funext z
            simp only [Function.comp_apply]
            change c * ((s : ℂ) * z) = (s : ℂ) * (R z)
            rw [show R z = c * z by rfl]
            ring
    _ = ((stdGaussian ℂ).map R).map (fun z : ℂ ↦ s • z) := by
            rw [Measure.map_map (by fun_prop) (by fun_prop)]
    _ = (stdGaussian ℂ).map (fun z : ℂ ↦ s • z) := by rw [hR]

theorem measurePreserving_circularGaussianVector_mul
    {k : ℕ} (c : ℂ) (hc : ‖c‖ = 1) :
    MeasurePreserving (fun x : Fin k → ℂ ↦ fun p ↦ c * x p)
      (circularGaussianVector k) (circularGaussianVector k) := by
  unfold circularGaussianVector
  exact measurePreserving_pi _ _ fun _ ↦
    measurePreserving_circularGaussian_mul c hc

theorem measurePreserving_finiteColumnFamily_mul
    {ι : Type*} [Fintype ι] {k : ℕ}
    (c : ℂ) (hc : ‖c‖ = 1) :
    MeasurePreserving
      (fun A : ι → (Fin k → ℂ) ↦ fun i p ↦ c * A i p)
      (Measure.pi fun _ : ι ↦ circularGaussianVector k)
      (Measure.pi fun _ : ι ↦ circularGaussianVector k) := by
  exact measurePreserving_pi _ _ fun _ ↦
    measurePreserving_circularGaussianVector_mul c hc

theorem finiteGramCofactorPhase_commonPhase
    {ι : Type*} [Fintype ι] [LinearOrder ι] {k d : ℕ}
    (hcard : Fintype.card ι = d + 1) (hdEven : ∃ r, d = 2 * r)
    (c : ℂ) (A : ι → (Fin k → ℂ)) (w : ι → ℂ) :
    finiteGramCofactorPhase (fun i p ↦ c * A i p) w =
      finiteGramCofactorPhase A (fun i ↦ c ^ d * w i) := by
  obtain ⟨r, rfl⟩ := hdEven
  unfold finiteGramCofactorPhase
  congr 1
  apply Finset.sum_congr rfl
  intro j _hj
  unfold finiteGramCofactorVector
  rw [columnTransposeGram_commonPhase]
  have hdelete : Fintype.card {i : ι // i ≠ j} = 2 * r := by
    rw [Fintype.card_subtype_compl]
    have hone : Fintype.card {i : ι // i = j} = 1 := by simp
    rw [hone, hcard]
    omega
  rw [typeHafnian_const_mul_of_card r hdelete, ← pow_mul]
  change w j * (c ^ (2 * r) * finiteGramCofactorVector A j) =
    c ^ (2 * r) * w j * finiteGramCofactorVector A j
  ring

theorem finiteGramCofactorCharacteristic_commonPhase
    {ι : Type*} [Fintype ι] [LinearOrder ι] {k d : ℕ}
    (hcard : Fintype.card ι = d + 1) (hdpos : 0 < d)
    (hdEven : ∃ r, d = 2 * r) (q : ℂ) (hq : ‖q‖ = 1)
    (w : ι → ℂ) :
    finiteGramCofactorCharacteristic ι k (fun i ↦ q * w i) =
      finiteGramCofactorCharacteristic ι k w := by
  obtain ⟨c, hcPow⟩ := IsAlgClosed.exists_pow_nat_eq q⁻¹ hdpos
  have hqne : q ≠ 0 := norm_ne_zero_iff.mp (by simpa [hq])
  have hcNormPow : ‖c‖ ^ d = 1 := by
    rw [← norm_pow, hcPow, norm_inv, hq, inv_one]
  have hcNorm : ‖c‖ = 1 := by
    exact (pow_eq_one_iff_of_nonneg (norm_nonneg c)
      (Nat.ne_of_gt hdpos)).mp hcNormPow
  have hcne : c ≠ 0 := norm_ne_zero_iff.mp (by simpa [hcNorm])
  let g : (ι → (Fin k → ℂ)) → (ι → (Fin k → ℂ)) :=
    fun A i p ↦ c * A i p
  have hg : MeasurePreserving g
      (Measure.pi fun _ : ι ↦ circularGaussianVector k)
      (Measure.pi fun _ : ι ↦ circularGaussianVector k) := by
    simpa [g] using measurePreserving_finiteColumnFamily_mul
      (ι := ι) (k := k) c hcNorm
  let μ : Measure (ι → (Fin k → ℂ)) :=
    Measure.pi fun _ : ι ↦ circularGaussianVector k
  change (∫ A, finiteGramCofactorPhaseCharacter (fun i ↦ q * w i) A ∂μ) =
    ∫ A, finiteGramCofactorPhaseCharacter w A ∂μ
  calc
    (∫ A, finiteGramCofactorPhaseCharacter (fun i ↦ q * w i) A ∂μ) =
        ∫ A, finiteGramCofactorPhaseCharacter (fun i ↦ q * w i) A
          ∂Measure.map g μ := by rw [hg.map_eq]
    _ = ∫ A, finiteGramCofactorPhaseCharacter (fun i ↦ q * w i) (g A)
          ∂μ := by
      exact integral_map hg.aemeasurable
        (measurable_finiteGramCofactorPhaseCharacter
          (k := k) (fun i ↦ q * w i)).aestronglyMeasurable
    _ = ∫ A, finiteGramCofactorPhaseCharacter w A ∂μ := by
      apply integral_congr_ae
      filter_upwards [] with A
      unfold finiteGramCofactorPhaseCharacter
      congr 2
      change (finiteGramCofactorPhase (fun i p ↦ c * A i p)
          (fun i ↦ q * w i) : ℂ) =
        (finiteGramCofactorPhase A w : ℂ)
      rw [finiteGramCofactorPhase_commonPhase
        (k := k) hcard hdEven c A (fun i ↦ q * w i)]
      congr 2
      funext i
      rw [hcPow]
      simp [hqne]

theorem finiteGramCofactorCharacteristic_singletonExchangeable
    {ι : Type*} [Fintype ι] [LinearOrder ι] {k : ℕ} :
    SingletonExchangeable (finiteGramCofactorCharacteristic ι k) := by
  intro i j z
  classical
  by_cases hij : i = j
  · subst j
    rfl
  let σ : Equiv.Perm ι := Equiv.swap i j
  have h := finiteGramCofactorCharacteristic_reindex_perm
    (k := k) σ (singleCoordinate j z)
  rw [show (fun l ↦ singleCoordinate j z (σ l)) =
      singleCoordinate i z by
    funext l
    by_cases hli : l = i
    · subst l
      simp [σ, singleCoordinate, hij]
    · by_cases hlj : l = j
      · subst l
        simp [σ, singleCoordinate, hij, hli]
      · rw [Equiv.swap_apply_of_ne_of_ne hli hlj]
        simp [singleCoordinate, hli, hlj]] at h
  exact h

theorem finiteGramCofactorCharacteristic_commonPhaseInvariant
    {ι : Type*} [Fintype ι] [LinearOrder ι] {k d : ℕ}
    (hcard : Fintype.card ι = d + 1) (hdpos : 0 < d)
    (hdEven : ∃ r, d = 2 * r) :
    CommonPhaseInvariant (finiteGramCofactorCharacteristic ι k) := by
  intro q hq w
  exact finiteGramCofactorCharacteristic_commonPhase
    hcard hdpos hdEven q hq w

/-- Exact symmetry bundle required by the finite-coordinate compression
iteration.  The only remaining input to that iteration is its local
two-coordinate inequality `hstep`. -/
theorem finiteGramCofactorCharacteristic_compression_symmetries
    {ι : Type*} [Fintype ι] [LinearOrder ι] {k d : ℕ}
    (hcard : Fintype.card ι = d + 1) (hdpos : 0 < d)
    (hdEven : ∃ r, d = 2 * r) :
    SingletonExchangeable (finiteGramCofactorCharacteristic ι k) ∧
      CommonPhaseInvariant (finiteGramCofactorCharacteristic ι k) :=
  ⟨finiteGramCofactorCharacteristic_singletonExchangeable,
    finiteGramCofactorCharacteristic_commonPhaseInvariant
      hcard hdpos hdEven⟩

end

end LogdetLean.GramHafnian
